/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BCA</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.BCA#getCATName <em>CAT Name</em>}</li>
 *   <li>{@link org.afplib.afpText.BCA#getTriplets <em>Triplets</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getBCA()
 * @model
 * @generated
 */
public interface BCA extends structuredField
{
  /**
   * Returns the value of the '<em><b>CAT Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>CAT Name</em>' attribute.
   * @see #setCATName(String)
   * @see org.afplib.afpText.AfpTextPackage#getBCA_CATName()
   * @model
   * @generated
   */
  String getCATName();

  /**
   * Sets the value of the '{@link org.afplib.afpText.BCA#getCATName <em>CAT Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>CAT Name</em>' attribute.
   * @see #getCATName()
   * @generated
   */
  void setCATName(String value);

  /**
   * Returns the value of the '<em><b>Triplets</b></em>' containment reference list.
   * The list contents are of type {@link org.afplib.afpText.triplet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Triplets</em>' containment reference list.
   * @see org.afplib.afpText.AfpTextPackage#getBCA_Triplets()
   * @model containment="true"
   * @generated
   */
  EList<triplet> getTriplets();

} // BCA
