/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Begin Segment Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.BeginSegmentCommand#getLENGTH <em>LENGTH</em>}</li>
 *   <li>{@link org.afplib.afpText.BeginSegmentCommand#getNAME <em>NAME</em>}</li>
 *   <li>{@link org.afplib.afpText.BeginSegmentCommand#getFLAG1 <em>FLAG1</em>}</li>
 *   <li>{@link org.afplib.afpText.BeginSegmentCommand#getFLAG2 <em>FLAG2</em>}</li>
 *   <li>{@link org.afplib.afpText.BeginSegmentCommand#getSEGL <em>SEGL</em>}</li>
 *   <li>{@link org.afplib.afpText.BeginSegmentCommand#getPSNAME <em>PSNAME</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getBeginSegmentCommand()
 * @model
 * @generated
 */
public interface BeginSegmentCommand extends triplet
{
  /**
   * Returns the value of the '<em><b>LENGTH</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>LENGTH</em>' attribute.
   * @see #setLENGTH(int)
   * @see org.afplib.afpText.AfpTextPackage#getBeginSegmentCommand_LENGTH()
   * @model
   * @generated
   */
  int getLENGTH();

  /**
   * Sets the value of the '{@link org.afplib.afpText.BeginSegmentCommand#getLENGTH <em>LENGTH</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>LENGTH</em>' attribute.
   * @see #getLENGTH()
   * @generated
   */
  void setLENGTH(int value);

  /**
   * Returns the value of the '<em><b>NAME</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>NAME</em>' attribute.
   * @see #setNAME(int)
   * @see org.afplib.afpText.AfpTextPackage#getBeginSegmentCommand_NAME()
   * @model
   * @generated
   */
  int getNAME();

  /**
   * Sets the value of the '{@link org.afplib.afpText.BeginSegmentCommand#getNAME <em>NAME</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>NAME</em>' attribute.
   * @see #getNAME()
   * @generated
   */
  void setNAME(int value);

  /**
   * Returns the value of the '<em><b>FLAG1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>FLAG1</em>' attribute.
   * @see #setFLAG1(int)
   * @see org.afplib.afpText.AfpTextPackage#getBeginSegmentCommand_FLAG1()
   * @model
   * @generated
   */
  int getFLAG1();

  /**
   * Sets the value of the '{@link org.afplib.afpText.BeginSegmentCommand#getFLAG1 <em>FLAG1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>FLAG1</em>' attribute.
   * @see #getFLAG1()
   * @generated
   */
  void setFLAG1(int value);

  /**
   * Returns the value of the '<em><b>FLAG2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>FLAG2</em>' attribute.
   * @see #setFLAG2(int)
   * @see org.afplib.afpText.AfpTextPackage#getBeginSegmentCommand_FLAG2()
   * @model
   * @generated
   */
  int getFLAG2();

  /**
   * Sets the value of the '{@link org.afplib.afpText.BeginSegmentCommand#getFLAG2 <em>FLAG2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>FLAG2</em>' attribute.
   * @see #getFLAG2()
   * @generated
   */
  void setFLAG2(int value);

  /**
   * Returns the value of the '<em><b>SEGL</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>SEGL</em>' attribute.
   * @see #setSEGL(int)
   * @see org.afplib.afpText.AfpTextPackage#getBeginSegmentCommand_SEGL()
   * @model
   * @generated
   */
  int getSEGL();

  /**
   * Sets the value of the '{@link org.afplib.afpText.BeginSegmentCommand#getSEGL <em>SEGL</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>SEGL</em>' attribute.
   * @see #getSEGL()
   * @generated
   */
  void setSEGL(int value);

  /**
   * Returns the value of the '<em><b>PSNAME</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>PSNAME</em>' attribute.
   * @see #setPSNAME(String)
   * @see org.afplib.afpText.AfpTextPackage#getBeginSegmentCommand_PSNAME()
   * @model
   * @generated
   */
  String getPSNAME();

  /**
   * Sets the value of the '{@link org.afplib.afpText.BeginSegmentCommand#getPSNAME <em>PSNAME</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>PSNAME</em>' attribute.
   * @see #getPSNAME()
   * @generated
   */
  void setPSNAME(String value);

} // BeginSegmentCommand
