/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BPT</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.BPT#getPTdoName <em>PTdo Name</em>}</li>
 *   <li>{@link org.afplib.afpText.BPT#getTriplets <em>Triplets</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getBPT()
 * @model
 * @generated
 */
public interface BPT extends structuredField
{
  /**
   * Returns the value of the '<em><b>PTdo Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>PTdo Name</em>' attribute.
   * @see #setPTdoName(String)
   * @see org.afplib.afpText.AfpTextPackage#getBPT_PTdoName()
   * @model
   * @generated
   */
  String getPTdoName();

  /**
   * Sets the value of the '{@link org.afplib.afpText.BPT#getPTdoName <em>PTdo Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>PTdo Name</em>' attribute.
   * @see #getPTdoName()
   * @generated
   */
  void setPTdoName(String value);

  /**
   * Returns the value of the '<em><b>Triplets</b></em>' containment reference list.
   * The list contents are of type {@link org.afplib.afpText.triplet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Triplets</em>' containment reference list.
   * @see org.afplib.afpText.AfpTextPackage#getBPT_Triplets()
   * @model containment="true"
   * @generated
   */
  EList<triplet> getTriplets();

} // BPT
