/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BSG</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.BSG#getREGName <em>REG Name</em>}</li>
 *   <li>{@link org.afplib.afpText.BSG#getTriplets <em>Triplets</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getBSG()
 * @model
 * @generated
 */
public interface BSG extends structuredField
{
  /**
   * Returns the value of the '<em><b>REG Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>REG Name</em>' attribute.
   * @see #setREGName(String)
   * @see org.afplib.afpText.AfpTextPackage#getBSG_REGName()
   * @model
   * @generated
   */
  String getREGName();

  /**
   * Sets the value of the '{@link org.afplib.afpText.BSG#getREGName <em>REG Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>REG Name</em>' attribute.
   * @see #getREGName()
   * @generated
   */
  void setREGName(String value);

  /**
   * Returns the value of the '<em><b>Triplets</b></em>' containment reference list.
   * The list contents are of type {@link org.afplib.afpText.triplet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Triplets</em>' containment reference list.
   * @see org.afplib.afpText.AfpTextPackage#getBSG_Triplets()
   * @model containment="true"
   * @generated
   */
  EList<triplet> getTriplets();

} // BSG
