/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BSU</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.BSU#getLID <em>LID</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getBSU()
 * @model
 * @generated
 */
public interface BSU extends triplet
{
  /**
   * Returns the value of the '<em><b>LID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>LID</em>' attribute.
   * @see #setLID(int)
   * @see org.afplib.afpText.AfpTextPackage#getBSU_LID()
   * @model
   * @generated
   */
  int getLID();

  /**
   * Sets the value of the '{@link org.afplib.afpText.BSU#getLID <em>LID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>LID</em>' attribute.
   * @see #getLID()
   * @generated
   */
  void setLID(int value);

} // BSU
