/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CRC Resource Management</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.CRCResourceManagement#getFmtQual <em>Fmt Qual</em>}</li>
 *   <li>{@link org.afplib.afpText.CRCResourceManagement#getRMValue <em>RM Value</em>}</li>
 *   <li>{@link org.afplib.afpText.CRCResourceManagement#getResClassFlg <em>Res Class Flg</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getCRCResourceManagement()
 * @model
 * @generated
 */
public interface CRCResourceManagement extends triplet
{
  /**
   * Returns the value of the '<em><b>Fmt Qual</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fmt Qual</em>' attribute.
   * @see #setFmtQual(int)
   * @see org.afplib.afpText.AfpTextPackage#getCRCResourceManagement_FmtQual()
   * @model
   * @generated
   */
  int getFmtQual();

  /**
   * Sets the value of the '{@link org.afplib.afpText.CRCResourceManagement#getFmtQual <em>Fmt Qual</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fmt Qual</em>' attribute.
   * @see #getFmtQual()
   * @generated
   */
  void setFmtQual(int value);

  /**
   * Returns the value of the '<em><b>RM Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>RM Value</em>' attribute.
   * @see #setRMValue(int)
   * @see org.afplib.afpText.AfpTextPackage#getCRCResourceManagement_RMValue()
   * @model
   * @generated
   */
  int getRMValue();

  /**
   * Sets the value of the '{@link org.afplib.afpText.CRCResourceManagement#getRMValue <em>RM Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>RM Value</em>' attribute.
   * @see #getRMValue()
   * @generated
   */
  void setRMValue(int value);

  /**
   * Returns the value of the '<em><b>Res Class Flg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Res Class Flg</em>' attribute.
   * @see #setResClassFlg(int)
   * @see org.afplib.afpText.AfpTextPackage#getCRCResourceManagement_ResClassFlg()
   * @model
   * @generated
   */
  int getResClassFlg();

  /**
   * Sets the value of the '{@link org.afplib.afpText.CRCResourceManagement#getResClassFlg <em>Res Class Flg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Res Class Flg</em>' attribute.
   * @see #getResClassFlg()
   * @generated
   */
  void setResClassFlg(int value);

} // CRCResourceManagement
