/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EDM</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.EDM#getDMName <em>DM Name</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getEDM()
 * @model
 * @generated
 */
public interface EDM extends structuredField
{
  /**
   * Returns the value of the '<em><b>DM Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>DM Name</em>' attribute.
   * @see #setDMName(String)
   * @see org.afplib.afpText.AfpTextPackage#getEDM_DMName()
   * @model
   * @generated
   */
  String getDMName();

  /**
   * Sets the value of the '{@link org.afplib.afpText.EDM#getDMName <em>DM Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>DM Name</em>' attribute.
   * @see #getDMName()
   * @generated
   */
  void setDMName(String value);

} // EDM
