/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EFN</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.EFN#getRSName <em>RS Name</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getEFN()
 * @model
 * @generated
 */
public interface EFN extends structuredField
{
  /**
   * Returns the value of the '<em><b>RS Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>RS Name</em>' attribute.
   * @see #setRSName(String)
   * @see org.afplib.afpText.AfpTextPackage#getEFN_RSName()
   * @model
   * @generated
   */
  String getRSName();

  /**
   * Sets the value of the '{@link org.afplib.afpText.EFN#getRSName <em>RS Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>RS Name</em>' attribute.
   * @see #getRSName()
   * @generated
   */
  void setRSName(String value);

} // EFN
