/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ESG</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.ESG#getREGName <em>REG Name</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getESG()
 * @model
 * @generated
 */
public interface ESG extends structuredField
{
  /**
   * Returns the value of the '<em><b>REG Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>REG Name</em>' attribute.
   * @see #setREGName(String)
   * @see org.afplib.afpText.AfpTextPackage#getESG_REGName()
   * @model
   * @generated
   */
  String getREGName();

  /**
   * Sets the value of the '{@link org.afplib.afpText.ESG#getREGName <em>REG Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>REG Name</em>' attribute.
   * @see #getREGName()
   * @generated
   */
  void setREGName(String value);

} // ESG
