/**
 * generated by Xtext 2.19.0
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GAD</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.GAD#getGOCAdat <em>GOC Adat</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getGAD()
 * @model
 * @generated
 */
public interface GAD extends structuredField
{
  /**
   * Returns the value of the '<em><b>GOC Adat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>GOC Adat</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>GOC Adat</em>' attribute.
   * @see #setGOCAdat(String)
   * @see org.afplib.afpText.AfpTextPackage#getGAD_GOCAdat()
   * @model
   * @generated
   */
  String getGOCAdat();

  /**
   * Sets the value of the '{@link org.afplib.afpText.GAD#getGOCAdat <em>GOC Adat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>GOC Adat</em>' attribute.
   * @see #getGOCAdat()
   * @generated
   */
  void setGOCAdat(String value);

} // GAD
