/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GCFLT</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.afplib.afpText.AfpTextPackage#getGCFLT()
 * @model
 * @generated
 */
public interface GCFLT extends triplet
{
} // GCFLT
