/**
 * generated by Xtext 2.19.0
 */
package org.afplib.afpText;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GCLINERG</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.GCLINERG#getXPOS <em>XPOS</em>}</li>
 *   <li>{@link org.afplib.afpText.GCLINERG#getYPOS <em>YPOS</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getGCLINERG()
 * @model
 * @generated
 */
public interface GCLINERG extends EObject
{
  /**
   * Returns the value of the '<em><b>XPOS</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>XPOS</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>XPOS</em>' attribute.
   * @see #setXPOS(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getGCLINERG_XPOS()
   * @model
   * @generated
   */
  Integer getXPOS();

  /**
   * Sets the value of the '{@link org.afplib.afpText.GCLINERG#getXPOS <em>XPOS</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>XPOS</em>' attribute.
   * @see #getXPOS()
   * @generated
   */
  void setXPOS(Integer value);

  /**
   * Returns the value of the '<em><b>YPOS</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>YPOS</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>YPOS</em>' attribute.
   * @see #setYPOS(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getGCLINERG_YPOS()
   * @model
   * @generated
   */
  Integer getYPOS();

  /**
   * Sets the value of the '{@link org.afplib.afpText.GCLINERG#getYPOS <em>YPOS</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>YPOS</em>' attribute.
   * @see #getYPOS()
   * @generated
   */
  void setYPOS(Integer value);

} // GCLINERG
