/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GSECOL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.GSECOL#getCOLOR <em>COLOR</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getGSECOL()
 * @model
 * @generated
 */
public interface GSECOL extends triplet
{
  /**
   * Returns the value of the '<em><b>COLOR</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>COLOR</em>' attribute.
   * @see #setCOLOR(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getGSECOL_COLOR()
   * @model
   * @generated
   */
  Integer getCOLOR();

  /**
   * Sets the value of the '{@link org.afplib.afpText.GSECOL#getCOLOR <em>COLOR</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>COLOR</em>' attribute.
   * @see #getCOLOR()
   * @generated
   */
  void setCOLOR(Integer value);

} // GSECOL
