/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Image Resolution</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.ImageResolution#getXBase <em>XBase</em>}</li>
 *   <li>{@link org.afplib.afpText.ImageResolution#getYBase <em>YBase</em>}</li>
 *   <li>{@link org.afplib.afpText.ImageResolution#getXResol <em>XResol</em>}</li>
 *   <li>{@link org.afplib.afpText.ImageResolution#getYResol <em>YResol</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getImageResolution()
 * @model
 * @generated
 */
public interface ImageResolution extends triplet
{
  /**
   * Returns the value of the '<em><b>XBase</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>XBase</em>' attribute.
   * @see #setXBase(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getImageResolution_XBase()
   * @model
   * @generated
   */
  Integer getXBase();

  /**
   * Sets the value of the '{@link org.afplib.afpText.ImageResolution#getXBase <em>XBase</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>XBase</em>' attribute.
   * @see #getXBase()
   * @generated
   */
  void setXBase(Integer value);

  /**
   * Returns the value of the '<em><b>YBase</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>YBase</em>' attribute.
   * @see #setYBase(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getImageResolution_YBase()
   * @model
   * @generated
   */
  Integer getYBase();

  /**
   * Sets the value of the '{@link org.afplib.afpText.ImageResolution#getYBase <em>YBase</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>YBase</em>' attribute.
   * @see #getYBase()
   * @generated
   */
  void setYBase(Integer value);

  /**
   * Returns the value of the '<em><b>XResol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>XResol</em>' attribute.
   * @see #setXResol(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getImageResolution_XResol()
   * @model
   * @generated
   */
  Integer getXResol();

  /**
   * Sets the value of the '{@link org.afplib.afpText.ImageResolution#getXResol <em>XResol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>XResol</em>' attribute.
   * @see #getXResol()
   * @generated
   */
  void setXResol(Integer value);

  /**
   * Returns the value of the '<em><b>YResol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>YResol</em>' attribute.
   * @see #setYResol(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getImageResolution_YResol()
   * @model
   * @generated
   */
  Integer getYResol();

  /**
   * Sets the value of the '{@link org.afplib.afpText.ImageResolution#getYResol <em>YResol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>YResol</em>' attribute.
   * @see #getYResol()
   * @generated
   */
  void setYResol(Integer value);

} // ImageResolution
