/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LLE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.LLE#getLnkType <em>Lnk Type</em>}</li>
 *   <li>{@link org.afplib.afpText.LLE#getRg <em>Rg</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getLLE()
 * @model
 * @generated
 */
public interface LLE extends structuredField
{
  /**
   * Returns the value of the '<em><b>Lnk Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lnk Type</em>' attribute.
   * @see #setLnkType(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getLLE_LnkType()
   * @model
   * @generated
   */
  Integer getLnkType();

  /**
   * Sets the value of the '{@link org.afplib.afpText.LLE#getLnkType <em>Lnk Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lnk Type</em>' attribute.
   * @see #getLnkType()
   * @generated
   */
  void setLnkType(Integer value);

  /**
   * Returns the value of the '<em><b>Rg</b></em>' containment reference list.
   * The list contents are of type {@link org.afplib.afpText.LLERG}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rg</em>' containment reference list.
   * @see org.afplib.afpText.AfpTextPackage#getLLE_Rg()
   * @model containment="true"
   * @generated
   */
  EList<LLERG> getRg();

} // LLE
