/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MFC</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.MFC#getMFCFlgs <em>MFC Flgs</em>}</li>
 *   <li>{@link org.afplib.afpText.MFC#getMedColl <em>Med Coll</em>}</li>
 *   <li>{@link org.afplib.afpText.MFC#getMFCScpe <em>MFC Scpe</em>}</li>
 *   <li>{@link org.afplib.afpText.MFC#getTriplets <em>Triplets</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getMFC()
 * @model
 * @generated
 */
public interface MFC extends structuredField
{
  /**
   * Returns the value of the '<em><b>MFC Flgs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>MFC Flgs</em>' attribute.
   * @see #setMFCFlgs(int)
   * @see org.afplib.afpText.AfpTextPackage#getMFC_MFCFlgs()
   * @model
   * @generated
   */
  int getMFCFlgs();

  /**
   * Sets the value of the '{@link org.afplib.afpText.MFC#getMFCFlgs <em>MFC Flgs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>MFC Flgs</em>' attribute.
   * @see #getMFCFlgs()
   * @generated
   */
  void setMFCFlgs(int value);

  /**
   * Returns the value of the '<em><b>Med Coll</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Med Coll</em>' attribute.
   * @see #setMedColl(int)
   * @see org.afplib.afpText.AfpTextPackage#getMFC_MedColl()
   * @model
   * @generated
   */
  int getMedColl();

  /**
   * Sets the value of the '{@link org.afplib.afpText.MFC#getMedColl <em>Med Coll</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Med Coll</em>' attribute.
   * @see #getMedColl()
   * @generated
   */
  void setMedColl(int value);

  /**
   * Returns the value of the '<em><b>MFC Scpe</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>MFC Scpe</em>' attribute.
   * @see #setMFCScpe(int)
   * @see org.afplib.afpText.AfpTextPackage#getMFC_MFCScpe()
   * @model
   * @generated
   */
  int getMFCScpe();

  /**
   * Sets the value of the '{@link org.afplib.afpText.MFC#getMFCScpe <em>MFC Scpe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>MFC Scpe</em>' attribute.
   * @see #getMFCScpe()
   * @generated
   */
  void setMFCScpe(int value);

  /**
   * Returns the value of the '<em><b>Triplets</b></em>' containment reference list.
   * The list contents are of type {@link org.afplib.afpText.triplet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Triplets</em>' containment reference list.
   * @see org.afplib.afpText.AfpTextPackage#getMFC_Triplets()
   * @model containment="true"
   * @generated
   */
  EList<triplet> getTriplets();

} // MFC
