/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Structured Field Offset</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.ObjectStructuredFieldOffset#getSFOff <em>SF Off</em>}</li>
 *   <li>{@link org.afplib.afpText.ObjectStructuredFieldOffset#getSFOffHi <em>SF Off Hi</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getObjectStructuredFieldOffset()
 * @model
 * @generated
 */
public interface ObjectStructuredFieldOffset extends triplet
{
  /**
   * Returns the value of the '<em><b>SF Off</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>SF Off</em>' attribute.
   * @see #setSFOff(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getObjectStructuredFieldOffset_SFOff()
   * @model
   * @generated
   */
  Integer getSFOff();

  /**
   * Sets the value of the '{@link org.afplib.afpText.ObjectStructuredFieldOffset#getSFOff <em>SF Off</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>SF Off</em>' attribute.
   * @see #getSFOff()
   * @generated
   */
  void setSFOff(Integer value);

  /**
   * Returns the value of the '<em><b>SF Off Hi</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>SF Off Hi</em>' attribute.
   * @see #setSFOffHi(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getObjectStructuredFieldOffset_SFOffHi()
   * @model
   * @generated
   */
  Integer getSFOffHi();

  /**
   * Sets the value of the '{@link org.afplib.afpText.ObjectStructuredFieldOffset#getSFOffHi <em>SF Off Hi</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>SF Off Hi</em>' attribute.
   * @see #getSFOffHi()
   * @generated
   */
  void setSFOffHi(Integer value);

} // ObjectStructuredFieldOffset
