/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PPORG</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.PPORG#getRGLength <em>RG Length</em>}</li>
 *   <li>{@link org.afplib.afpText.PPORG#getObjType <em>Obj Type</em>}</li>
 *   <li>{@link org.afplib.afpText.PPORG#getProcFlgs <em>Proc Flgs</em>}</li>
 *   <li>{@link org.afplib.afpText.PPORG#getXocaOset <em>Xoca Oset</em>}</li>
 *   <li>{@link org.afplib.afpText.PPORG#getYocaOset <em>Yoca Oset</em>}</li>
 *   <li>{@link org.afplib.afpText.PPORG#getTriplets <em>Triplets</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getPPORG()
 * @model
 * @generated
 */
public interface PPORG extends EObject
{
  /**
   * Returns the value of the '<em><b>RG Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>RG Length</em>' attribute.
   * @see #setRGLength(int)
   * @see org.afplib.afpText.AfpTextPackage#getPPORG_RGLength()
   * @model
   * @generated
   */
  int getRGLength();

  /**
   * Sets the value of the '{@link org.afplib.afpText.PPORG#getRGLength <em>RG Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>RG Length</em>' attribute.
   * @see #getRGLength()
   * @generated
   */
  void setRGLength(int value);

  /**
   * Returns the value of the '<em><b>Obj Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obj Type</em>' attribute.
   * @see #setObjType(int)
   * @see org.afplib.afpText.AfpTextPackage#getPPORG_ObjType()
   * @model
   * @generated
   */
  int getObjType();

  /**
   * Sets the value of the '{@link org.afplib.afpText.PPORG#getObjType <em>Obj Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obj Type</em>' attribute.
   * @see #getObjType()
   * @generated
   */
  void setObjType(int value);

  /**
   * Returns the value of the '<em><b>Proc Flgs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Proc Flgs</em>' attribute.
   * @see #setProcFlgs(int)
   * @see org.afplib.afpText.AfpTextPackage#getPPORG_ProcFlgs()
   * @model
   * @generated
   */
  int getProcFlgs();

  /**
   * Sets the value of the '{@link org.afplib.afpText.PPORG#getProcFlgs <em>Proc Flgs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Proc Flgs</em>' attribute.
   * @see #getProcFlgs()
   * @generated
   */
  void setProcFlgs(int value);

  /**
   * Returns the value of the '<em><b>Xoca Oset</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xoca Oset</em>' attribute.
   * @see #setXocaOset(int)
   * @see org.afplib.afpText.AfpTextPackage#getPPORG_XocaOset()
   * @model
   * @generated
   */
  int getXocaOset();

  /**
   * Sets the value of the '{@link org.afplib.afpText.PPORG#getXocaOset <em>Xoca Oset</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Xoca Oset</em>' attribute.
   * @see #getXocaOset()
   * @generated
   */
  void setXocaOset(int value);

  /**
   * Returns the value of the '<em><b>Yoca Oset</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Yoca Oset</em>' attribute.
   * @see #setYocaOset(int)
   * @see org.afplib.afpText.AfpTextPackage#getPPORG_YocaOset()
   * @model
   * @generated
   */
  int getYocaOset();

  /**
   * Sets the value of the '{@link org.afplib.afpText.PPORG#getYocaOset <em>Yoca Oset</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Yoca Oset</em>' attribute.
   * @see #getYocaOset()
   * @generated
   */
  void setYocaOset(int value);

  /**
   * Returns the value of the '<em><b>Triplets</b></em>' containment reference list.
   * The list contents are of type {@link org.afplib.afpText.triplet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Triplets</em>' containment reference list.
   * @see org.afplib.afpText.AfpTextPackage#getPPORG_Triplets()
   * @model containment="true"
   * @generated
   */
  EList<triplet> getTriplets();

} // PPORG
