/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PTX</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.afplib.afpText.AfpTextPackage#getPTX()
 * @model
 * @generated
 */
public interface PTX extends structuredField
{
} // PTX
