/**
 * generated by Xtext 2.19.0
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RMI</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.RMI#getINCRMENT <em>INCRMENT</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getRMI()
 * @model
 * @generated
 */
public interface RMI extends triplet
{
  /**
   * Returns the value of the '<em><b>INCRMENT</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>INCRMENT</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>INCRMENT</em>' attribute.
   * @see #setINCRMENT(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getRMI_INCRMENT()
   * @model
   * @generated
   */
  Integer getINCRMENT();

  /**
   * Sets the value of the '{@link org.afplib.afpText.RMI#getINCRMENT <em>INCRMENT</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>INCRMENT</em>' attribute.
   * @see #getINCRMENT()
   * @generated
   */
  void setINCRMENT(Integer value);

} // RMI
