/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SIA</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.SIA#getADJSTMNT <em>ADJSTMNT</em>}</li>
 *   <li>{@link org.afplib.afpText.SIA#getDIRCTION <em>DIRCTION</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getSIA()
 * @model
 * @generated
 */
public interface SIA extends triplet
{
  /**
   * Returns the value of the '<em><b>ADJSTMNT</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>ADJSTMNT</em>' attribute.
   * @see #setADJSTMNT(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getSIA_ADJSTMNT()
   * @model
   * @generated
   */
  Integer getADJSTMNT();

  /**
   * Sets the value of the '{@link org.afplib.afpText.SIA#getADJSTMNT <em>ADJSTMNT</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>ADJSTMNT</em>' attribute.
   * @see #getADJSTMNT()
   * @generated
   */
  void setADJSTMNT(Integer value);

  /**
   * Returns the value of the '<em><b>DIRCTION</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>DIRCTION</em>' attribute.
   * @see #setDIRCTION(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getSIA_DIRCTION()
   * @model
   * @generated
   */
  Integer getDIRCTION();

  /**
   * Sets the value of the '{@link org.afplib.afpText.SIA#getDIRCTION <em>DIRCTION</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>DIRCTION</em>' attribute.
   * @see #getDIRCTION()
   * @generated
   */
  void setDIRCTION(Integer value);

} // SIA
