/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text Orientation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.TextOrientation#getIAxis <em>IAxis</em>}</li>
 *   <li>{@link org.afplib.afpText.TextOrientation#getBAxis <em>BAxis</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getTextOrientation()
 * @model
 * @generated
 */
public interface TextOrientation extends triplet
{
  /**
   * Returns the value of the '<em><b>IAxis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>IAxis</em>' attribute.
   * @see #setIAxis(int)
   * @see org.afplib.afpText.AfpTextPackage#getTextOrientation_IAxis()
   * @model
   * @generated
   */
  int getIAxis();

  /**
   * Sets the value of the '{@link org.afplib.afpText.TextOrientation#getIAxis <em>IAxis</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>IAxis</em>' attribute.
   * @see #getIAxis()
   * @generated
   */
  void setIAxis(int value);

  /**
   * Returns the value of the '<em><b>BAxis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>BAxis</em>' attribute.
   * @see #setBAxis(int)
   * @see org.afplib.afpText.AfpTextPackage#getTextOrientation_BAxis()
   * @model
   * @generated
   */
  int getBAxis();

  /**
   * Sets the value of the '{@link org.afplib.afpText.TextOrientation#getBAxis <em>BAxis</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>BAxis</em>' attribute.
   * @see #getBAxis()
   * @generated
   */
  void setBAxis(int value);

} // TextOrientation
