/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tile Size</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.TileSize#getTHSIZE <em>THSIZE</em>}</li>
 *   <li>{@link org.afplib.afpText.TileSize#getTVSIZE <em>TVSIZE</em>}</li>
 *   <li>{@link org.afplib.afpText.TileSize#getRELRES <em>RELRES</em>}</li>
 * </ul>
 *
 * @see org.afplib.afpText.AfpTextPackage#getTileSize()
 * @model
 * @generated
 */
public interface TileSize extends triplet
{
  /**
   * Returns the value of the '<em><b>THSIZE</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>THSIZE</em>' attribute.
   * @see #setTHSIZE(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getTileSize_THSIZE()
   * @model
   * @generated
   */
  Integer getTHSIZE();

  /**
   * Sets the value of the '{@link org.afplib.afpText.TileSize#getTHSIZE <em>THSIZE</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>THSIZE</em>' attribute.
   * @see #getTHSIZE()
   * @generated
   */
  void setTHSIZE(Integer value);

  /**
   * Returns the value of the '<em><b>TVSIZE</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>TVSIZE</em>' attribute.
   * @see #setTVSIZE(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getTileSize_TVSIZE()
   * @model
   * @generated
   */
  Integer getTVSIZE();

  /**
   * Sets the value of the '{@link org.afplib.afpText.TileSize#getTVSIZE <em>TVSIZE</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>TVSIZE</em>' attribute.
   * @see #getTVSIZE()
   * @generated
   */
  void setTVSIZE(Integer value);

  /**
   * Returns the value of the '<em><b>RELRES</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>RELRES</em>' attribute.
   * @see #setRELRES(Integer)
   * @see org.afplib.afpText.AfpTextPackage#getTileSize_RELRES()
   * @model
   * @generated
   */
  Integer getRELRES();

  /**
   * Sets the value of the '{@link org.afplib.afpText.TileSize#getRELRES <em>RELRES</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>RELRES</em>' attribute.
   * @see #getRELRES()
   * @generated
   */
  void setRELRES(Integer value);

} // TileSize
