/**
 * generated by Xtext 2.19.0
 */
package org.afplib.afpText.impl;

import org.afplib.afpText.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class AfpTextFactoryImpl extends EFactoryImpl implements AfpTextFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static AfpTextFactory init()
  {
    try
    {
      AfpTextFactory theAfpTextFactory = (AfpTextFactory)EPackage.Registry.INSTANCE.getEFactory(AfpTextPackage.eNS_URI);
      if (theAfpTextFactory != null)
      {
        return theAfpTextFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new AfpTextFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AfpTextFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case AfpTextPackage.MODEL: return createModel();
      case AfpTextPackage.STRUCTURED_FIELD: return createstructuredField();
      case AfpTextPackage.LINE_DATA: return createLineData();
      case AfpTextPackage.BAG: return createBAG();
      case AfpTextPackage.BBC: return createBBC();
      case AfpTextPackage.BCA: return createBCA();
      case AfpTextPackage.BCF: return createBCF();
      case AfpTextPackage.BCP: return createBCP();
      case AfpTextPackage.BDA: return createBDA();
      case AfpTextPackage.BDD: return createBDD();
      case AfpTextPackage.BDG: return createBDG();
      case AfpTextPackage.BDI: return createBDI();
      case AfpTextPackage.BDM: return createBDM();
      case AfpTextPackage.BDT: return createBDT();
      case AfpTextPackage.BDX: return createBDX();
      case AfpTextPackage.BFG: return createBFG();
      case AfpTextPackage.BFM: return createBFM();
      case AfpTextPackage.BFN: return createBFN();
      case AfpTextPackage.BGR: return createBGR();
      case AfpTextPackage.BII: return createBII();
      case AfpTextPackage.BIM: return createBIM();
      case AfpTextPackage.BMM: return createBMM();
      case AfpTextPackage.BMO: return createBMO();
      case AfpTextPackage.BNG: return createBNG();
      case AfpTextPackage.BOC: return createBOC();
      case AfpTextPackage.BOG: return createBOG();
      case AfpTextPackage.BPF: return createBPF();
      case AfpTextPackage.BPG: return createBPG();
      case AfpTextPackage.BPM: return createBPM();
      case AfpTextPackage.BPS: return createBPS();
      case AfpTextPackage.BPT: return createBPT();
      case AfpTextPackage.BRG: return createBRG();
      case AfpTextPackage.BRS: return createBRS();
      case AfpTextPackage.BSG: return createBSG();
      case AfpTextPackage.CAT: return createCAT();
      case AfpTextPackage.CDD: return createCDD();
      case AfpTextPackage.CFC: return createCFC();
      case AfpTextPackage.CFI: return createCFI();
      case AfpTextPackage.CPC: return createCPC();
      case AfpTextPackage.CPD: return createCPD();
      case AfpTextPackage.CPI: return createCPI();
      case AfpTextPackage.CTC: return createCTC();
      case AfpTextPackage.DXD: return createDXD();
      case AfpTextPackage.EAG: return createEAG();
      case AfpTextPackage.EBC: return createEBC();
      case AfpTextPackage.ECA: return createECA();
      case AfpTextPackage.ECF: return createECF();
      case AfpTextPackage.ECP: return createECP();
      case AfpTextPackage.EDG: return createEDG();
      case AfpTextPackage.EDI: return createEDI();
      case AfpTextPackage.EDM: return createEDM();
      case AfpTextPackage.EDT: return createEDT();
      case AfpTextPackage.EDX: return createEDX();
      case AfpTextPackage.EFG: return createEFG();
      case AfpTextPackage.EFM: return createEFM();
      case AfpTextPackage.EFN: return createEFN();
      case AfpTextPackage.EGR: return createEGR();
      case AfpTextPackage.EII: return createEII();
      case AfpTextPackage.EIM: return createEIM();
      case AfpTextPackage.EMM: return createEMM();
      case AfpTextPackage.EMO: return createEMO();
      case AfpTextPackage.ENG: return createENG();
      case AfpTextPackage.EOC: return createEOC();
      case AfpTextPackage.EOG: return createEOG();
      case AfpTextPackage.EPF: return createEPF();
      case AfpTextPackage.EPG: return createEPG();
      case AfpTextPackage.EPM: return createEPM();
      case AfpTextPackage.EPS: return createEPS();
      case AfpTextPackage.EPT: return createEPT();
      case AfpTextPackage.ERG: return createERG();
      case AfpTextPackage.ERS: return createERS();
      case AfpTextPackage.ESG: return createESG();
      case AfpTextPackage.FNC: return createFNC();
      case AfpTextPackage.FND: return createFND();
      case AfpTextPackage.FNG: return createFNG();
      case AfpTextPackage.FNI: return createFNI();
      case AfpTextPackage.FNN: return createFNN();
      case AfpTextPackage.FNM: return createFNM();
      case AfpTextPackage.FNO: return createFNO();
      case AfpTextPackage.FNP: return createFNP();
      case AfpTextPackage.GAD: return createGAD();
      case AfpTextPackage.GDD: return createGDD();
      case AfpTextPackage.ICP: return createICP();
      case AfpTextPackage.IDD: return createIDD();
      case AfpTextPackage.IEL: return createIEL();
      case AfpTextPackage.IID: return createIID();
      case AfpTextPackage.IMM: return createIMM();
      case AfpTextPackage.IOB: return createIOB();
      case AfpTextPackage.IOC: return createIOC();
      case AfpTextPackage.IPD: return createIPD();
      case AfpTextPackage.IPG: return createIPG();
      case AfpTextPackage.IPO: return createIPO();
      case AfpTextPackage.IPS: return createIPS();
      case AfpTextPackage.IRD: return createIRD();
      case AfpTextPackage.LLE: return createLLE();
      case AfpTextPackage.LNC: return createLNC();
      case AfpTextPackage.LND: return createLND();
      case AfpTextPackage.MBC: return createMBC();
      case AfpTextPackage.MCA: return createMCA();
      case AfpTextPackage.MCC: return createMCC();
      case AfpTextPackage.MCD: return createMCD();
      case AfpTextPackage.MCF: return createMCF();
      case AfpTextPackage.MCF1: return createMCF1();
      case AfpTextPackage.MDD: return createMDD();
      case AfpTextPackage.MDR: return createMDR();
      case AfpTextPackage.MFC: return createMFC();
      case AfpTextPackage.MGO: return createMGO();
      case AfpTextPackage.MIO: return createMIO();
      case AfpTextPackage.MMC: return createMMC();
      case AfpTextPackage.MMD: return createMMD();
      case AfpTextPackage.MMO: return createMMO();
      case AfpTextPackage.MMT: return createMMT();
      case AfpTextPackage.MPG: return createMPG();
      case AfpTextPackage.MPO: return createMPO();
      case AfpTextPackage.MPS: return createMPS();
      case AfpTextPackage.MSU: return createMSU();
      case AfpTextPackage.NOP: return createNOP();
      case AfpTextPackage.OBD: return createOBD();
      case AfpTextPackage.OBP: return createOBP();
      case AfpTextPackage.OCD: return createOCD();
      case AfpTextPackage.PEC: return createPEC();
      case AfpTextPackage.PFC: return createPFC();
      case AfpTextPackage.PGD: return createPGD();
      case AfpTextPackage.PGP: return createPGP();
      case AfpTextPackage.PGP1: return createPGP1();
      case AfpTextPackage.PMC: return createPMC();
      case AfpTextPackage.PPO: return createPPO();
      case AfpTextPackage.PTD: return createPTD();
      case AfpTextPackage.PTD1: return createPTD1();
      case AfpTextPackage.PTX: return createPTX();
      case AfpTextPackage.TLE: return createTLE();
      case AfpTextPackage.FGD: return createFGD();
      case AfpTextPackage.CPIRG: return createCPIRG();
      case AfpTextPackage.CFIRG: return createCFIRG();
      case AfpTextPackage.FNIRG: return createFNIRG();
      case AfpTextPackage.FNMRG: return createFNMRG();
      case AfpTextPackage.LLERG: return createLLERG();
      case AfpTextPackage.MPSRG: return createMPSRG();
      case AfpTextPackage.MCFRG: return createMCFRG();
      case AfpTextPackage.MBCRG: return createMBCRG();
      case AfpTextPackage.MCARG: return createMCARG();
      case AfpTextPackage.MCDRG: return createMCDRG();
      case AfpTextPackage.MDRRG: return createMDRRG();
      case AfpTextPackage.MGORG: return createMGORG();
      case AfpTextPackage.MIORG: return createMIORG();
      case AfpTextPackage.MMDRG: return createMMDRG();
      case AfpTextPackage.MMTRG: return createMMTRG();
      case AfpTextPackage.MPGRG: return createMPGRG();
      case AfpTextPackage.MPORG: return createMPORG();
      case AfpTextPackage.PPORG: return createPPORG();
      case AfpTextPackage.PGPRG: return createPGPRG();
      case AfpTextPackage.MCCRG: return createMCCRG();
      case AfpTextPackage.MMORG: return createMMORG();
      case AfpTextPackage.BAND_IMAGE_RG: return createBandImageRG();
      case AfpTextPackage.MCF1RG: return createMCF1RG();
      case AfpTextPackage.MMCRG: return createMMCRG();
      case AfpTextPackage.FNORG: return createFNORG();
      case AfpTextPackage.FNPRG: return createFNPRG();
      case AfpTextPackage.TILE_TOCRG: return createTileTOCRG();
      case AfpTextPackage.SAMPLING_RATIOS_RG: return createSamplingRatiosRG();
      case AfpTextPackage.EXTERNAL_ALGORITHM_RG: return createExternalAlgorithmRG();
      case AfpTextPackage.FNNRG: return createFNNRG();
      case AfpTextPackage.GCBEZRG: return createGCBEZRG();
      case AfpTextPackage.GCCBEZRG: return createGCCBEZRG();
      case AfpTextPackage.GFLTRG: return createGFLTRG();
      case AfpTextPackage.GCFLTRG: return createGCFLTRG();
      case AfpTextPackage.GLINERG: return createGLINERG();
      case AfpTextPackage.GCLINERG: return createGCLINERG();
      case AfpTextPackage.GMRKRG: return createGMRKRG();
      case AfpTextPackage.GCMRKRG: return createGCMRKRG();
      case AfpTextPackage.GRLINERG: return createGRLINERG();
      case AfpTextPackage.GCRLINERG: return createGCRLINERG();
      case AfpTextPackage.MSURG: return createMSURG();
      case AfpTextPackage.TRIPLET: return createtriplet();
      case AfpTextPackage.AMB: return createAMB();
      case AfpTextPackage.AMI: return createAMI();
      case AfpTextPackage.BLN: return createBLN();
      case AfpTextPackage.BSU: return createBSU();
      case AfpTextPackage.DBR: return createDBR();
      case AfpTextPackage.DIR: return createDIR();
      case AfpTextPackage.ESU: return createESU();
      case AfpTextPackage.NOPCS: return createNOPCS();
      case AfpTextPackage.OVS: return createOVS();
      case AfpTextPackage.RMB: return createRMB();
      case AfpTextPackage.RMI: return createRMI();
      case AfpTextPackage.RPS: return createRPS();
      case AfpTextPackage.SBI: return createSBI();
      case AfpTextPackage.SCFL: return createSCFL();
      case AfpTextPackage.SEC: return createSEC();
      case AfpTextPackage.SIA: return createSIA();
      case AfpTextPackage.SIM: return createSIM();
      case AfpTextPackage.STC: return createSTC();
      case AfpTextPackage.STO: return createSTO();
      case AfpTextPackage.SVI: return createSVI();
      case AfpTextPackage.TBM: return createTBM();
      case AfpTextPackage.TRN: return createTRN();
      case AfpTextPackage.USC: return createUSC();
      case AfpTextPackage.ATTRIBUTE_QUALIFIER: return createAttributeQualifier();
      case AfpTextPackage.ATTRIBUTE_VALUE: return createAttributeValue();
      case AfpTextPackage.CGCSGID: return createCGCSGID();
      case AfpTextPackage.CRC_RESOURCE_MANAGEMENT: return createCRCResourceManagement();
      case AfpTextPackage.CHARACTER_ROTATION: return createCharacterRotation();
      case AfpTextPackage.COLOR_SPECIFICATION: return createColorSpecification();
      case AfpTextPackage.COMMENT: return createComment();
      case AfpTextPackage.DATA_OBJECT_FONT_DESCRIPTOR: return createDataObjectFontDescriptor();
      case AfpTextPackage.DESCRIPTOR_POSITION: return createDescriptorPosition();
      case AfpTextPackage.ENCODING_SCHEME_ID: return createEncodingSchemeID();
      case AfpTextPackage.FONT_RESOLUTION: return createFontResolution();
      case AfpTextPackage.FULLY_QUALIFIED_NAME: return createFullyQualifiedName();
      case AfpTextPackage.LOCAL_DATE_AND_TIME_STAMP: return createLocalDateAndTimeStamp();
      case AfpTextPackage.UNIVERSAL_DATE_AND_TIME_STAMP: return createUniversalDateAndTimeStamp();
      case AfpTextPackage.MAPPING_OPTION: return createMappingOption();
      case AfpTextPackage.MEDIA_EJECT_CONTROL: return createMediaEjectControl();
      case AfpTextPackage.MEDIUM_MAP_PAGE_NUMBER: return createMediumMapPageNumber();
      case AfpTextPackage.MEDIUM_ORIENTATION: return createMediumOrientation();
      case AfpTextPackage.MEASUREMENT_UNITS: return createMeasurementUnits();
      case AfpTextPackage.MODCA_INTERCHANGE_SET: return createMODCAInterchangeSet();
      case AfpTextPackage.OBJECT_AREA_SIZE: return createObjectAreaSize();
      case AfpTextPackage.OBJECT_CLASSIFICATION: return createObjectClassification();
      case AfpTextPackage.OBJECT_FUNCTION_SET_SPECIFICATION: return createObjectFunctionSetSpecification();
      case AfpTextPackage.OBJECT_OFFSET: return createObjectOffset();
      case AfpTextPackage.RESOURCE_OBJECT_TYPE: return createResourceObjectType();
      case AfpTextPackage.PAGE_POSITION_INFORMATION: return createPagePositionInformation();
      case AfpTextPackage.PRESENTATION_CONTROL: return createPresentationControl();
      case AfpTextPackage.PRESENTATION_SPACE_RESET_MIXING: return createPresentationSpaceResetMixing();
      case AfpTextPackage.PRESENTATION_SPACE_MIXING_RULES: return createPresentationSpaceMixingRules();
      case AfpTextPackage.RESOURCE_LOCAL_IDENTIFIER: return createResourceLocalIdentifier();
      case AfpTextPackage.RESOURCE_SECTION_NUMBER: return createResourceSectionNumber();
      case AfpTextPackage.TEXT_ORIENTATION: return createTextOrientation();
      case AfpTextPackage.FONT_HORIZONTAL_SCALE_FACTOR: return createFontHorizontalScaleFactor();
      case AfpTextPackage.FONT_DESCRIPTOR_SPECIFICATION: return createFontDescriptorSpecification();
      case AfpTextPackage.BEGIN_SEGMENT: return createBeginSegment();
      case AfpTextPackage.END_SEGMENT: return createEndSegment();
      case AfpTextPackage.BEGIN_TILE: return createBeginTile();
      case AfpTextPackage.END_TILE: return createEndTile();
      case AfpTextPackage.BEGIN_TRANSPARENCY_MASK: return createBeginTransparencyMask();
      case AfpTextPackage.END_TRANSPARENCY_MASK: return createEndTransparencyMask();
      case AfpTextPackage.BEGIN_IMAGE: return createBeginImage();
      case AfpTextPackage.END_IMAGE: return createEndImage();
      case AfpTextPackage.IMAGE_SIZE: return createImageSize();
      case AfpTextPackage.IMAGE_ENCODING: return createImageEncoding();
      case AfpTextPackage.IDE_SIZE: return createIDESize();
      case AfpTextPackage.IMAGE_LUTID: return createImageLUTID();
      case AfpTextPackage.BAND_IMAGE: return createBandImage();
      case AfpTextPackage.IDE_STRUCTURE: return createIDEStructure();
      case AfpTextPackage.EXTERNAL_ALGORITHM: return createExternalAlgorithm();
      case AfpTextPackage.TILE_POSITION: return createTilePosition();
      case AfpTextPackage.TILE_SIZE: return createTileSize();
      case AfpTextPackage.TILE_SET_COLOR: return createTileSetColor();
      case AfpTextPackage.SET_BI_LEVEL_IMAGE_COLOR: return createSetBiLevelImageColor();
      case AfpTextPackage.IOCA_FUNCTION_SET_IDENTIFICATION: return createIOCAFunctionSetIdentification();
      case AfpTextPackage.IMAGE_DATA: return createImageData();
      case AfpTextPackage.BAND_IMAGE_DATA: return createBandImageData();
      case AfpTextPackage.INCLUDE_TILE: return createIncludeTile();
      case AfpTextPackage.IMAGE_SUBSAMPLING: return createImageSubsampling();
      case AfpTextPackage.SAMPLING_RATIOS: return createSamplingRatios();
      case AfpTextPackage.TILE_TOC: return createTileTOC();
      case AfpTextPackage.FNNRG2: return createFNNRG2();
      case AfpTextPackage.BEGIN_SEGMENT_COMMAND: return createBeginSegmentCommand();
      case AfpTextPackage.END_SEGMENT_COMMAND: return createEndSegmentCommand();
      case AfpTextPackage.GBAR: return createGBAR();
      case AfpTextPackage.GBIMG: return createGBIMG();
      case AfpTextPackage.GCBIMG: return createGCBIMG();
      case AfpTextPackage.GBOX: return createGBOX();
      case AfpTextPackage.GCBOX: return createGCBOX();
      case AfpTextPackage.GCHST: return createGCHST();
      case AfpTextPackage.GCCHST: return createGCCHST();
      case AfpTextPackage.GCOMT: return createGCOMT();
      case AfpTextPackage.GEAR: return createGEAR();
      case AfpTextPackage.GEIMG: return createGEIMG();
      case AfpTextPackage.GEPROL: return createGEPROL();
      case AfpTextPackage.GFLT: return createGFLT();
      case AfpTextPackage.GCFLT: return createGCFLT();
      case AfpTextPackage.GFARC: return createGFARC();
      case AfpTextPackage.GCFARC: return createGCFARC();
      case AfpTextPackage.GIMD: return createGIMD();
      case AfpTextPackage.GLINE: return createGLINE();
      case AfpTextPackage.GCLINE: return createGCLINE();
      case AfpTextPackage.GMRK: return createGMRK();
      case AfpTextPackage.GCMRK: return createGCMRK();
      case AfpTextPackage.GNOP1: return createGNOP1();
      case AfpTextPackage.GPARC: return createGPARC();
      case AfpTextPackage.GCPARC: return createGCPARC();
      case AfpTextPackage.GRLINE: return createGRLINE();
      case AfpTextPackage.GCRLINE: return createGCRLINE();
      case AfpTextPackage.GSGCH: return createGSGCH();
      case AfpTextPackage.GSAP: return createGSAP();
      case AfpTextPackage.GSBMX: return createGSBMX();
      case AfpTextPackage.GSCA: return createGSCA();
      case AfpTextPackage.GSCC: return createGSCC();
      case AfpTextPackage.GSCD: return createGSCD();
      case AfpTextPackage.GSCR: return createGSCR();
      case AfpTextPackage.GSCS: return createGSCS();
      case AfpTextPackage.GSCH: return createGSCH();
      case AfpTextPackage.GSCOL: return createGSCOL();
      case AfpTextPackage.GSCP: return createGSCP();
      case AfpTextPackage.GSECOL: return createGSECOL();
      case AfpTextPackage.GSFLW: return createGSFLW();
      case AfpTextPackage.GSLT: return createGSLT();
      case AfpTextPackage.GSLW: return createGSLW();
      case AfpTextPackage.GSMC: return createGSMC();
      case AfpTextPackage.GSMP: return createGSMP();
      case AfpTextPackage.GSMS: return createGSMS();
      case AfpTextPackage.GSMT: return createGSMT();
      case AfpTextPackage.GSMX: return createGSMX();
      case AfpTextPackage.GSPS: return createGSPS();
      case AfpTextPackage.GSPT: return createGSPT();
      case AfpTextPackage.GSPCOL: return createGSPCOL();
      case AfpTextPackage.GSLE: return createGSLE();
      case AfpTextPackage.GSLJ: return createGSLJ();
      case AfpTextPackage.GCBEZ: return createGCBEZ();
      case AfpTextPackage.GCCBEZ: return createGCCBEZ();
      case AfpTextPackage.WINDOW_SPECIFICATION: return createWindowSpecification();
      case AfpTextPackage.DRAWING_ORDER_SUBSET: return createDrawingOrderSubset();
      case AfpTextPackage.TONER_SAVER: return createTonerSaver();
      case AfpTextPackage.COLOR_FIDELITY: return createColorFidelity();
      case AfpTextPackage.FONT_FIDELITY: return createFontFidelity();
      case AfpTextPackage.TEXT_FIDELITY: return createTextFidelity();
      case AfpTextPackage.MEDIA_FIDELITY: return createMediaFidelity();
      case AfpTextPackage.FINISHING_FIDELITY: return createFinishingFidelity();
      case AfpTextPackage.CMR_FIDELITY: return createCMRFidelity();
      case AfpTextPackage.OBJECT_BYTE_EXTENT: return createObjectByteExtent();
      case AfpTextPackage.OBJECT_BYTE_OFFSET: return createObjectByteOffset();
      case AfpTextPackage.OBJECT_STRUCTURED_FIELD_EXTENT: return createObjectStructuredFieldExtent();
      case AfpTextPackage.OBJECT_STRUCTURED_FIELD_OFFSET: return createObjectStructuredFieldOffset();
      case AfpTextPackage.OBJECT_COUNT: return createObjectCount();
      case AfpTextPackage.OBJECT_ORIGIN_IDENTIFIER: return createObjectOriginIdentifier();
      case AfpTextPackage.LINE_DATA_OBJECT_POSITION_MIGRATION: return createLineDataObjectPositionMigration();
      case AfpTextPackage.COLOR_MANAGEMENT_RESOURCE_DESCRIPTOR: return createColorManagementResourceDescriptor();
      case AfpTextPackage.IMAGE_RESOLUTION: return createImageResolution();
      case AfpTextPackage.OBJECT_CONTAINER_PRESENTATION_SPACE_SIZE: return createObjectContainerPresentationSpaceSize();
      case AfpTextPackage.EXTENDED_RESOURCE_LOCAL_IDENTIFIER: return createExtendedResourceLocalIdentifier();
      case AfpTextPackage.METRIC_ADJUSTMENT: return createMetricAdjustment();
      case AfpTextPackage.EXTENSION_FONT: return createExtensionFont();
      case AfpTextPackage.RENDERING_INTENT: return createRenderingIntent();
      case AfpTextPackage.FONT_CODED_GRAPHIC_CHARACTER_SET_GLOBAL_IDENTIFIER: return createFontCodedGraphicCharacterSetGlobalIdentifier();
      case AfpTextPackage.LOCALE_SELECTOR: return createLocaleSelector();
      case AfpTextPackage.FINISHING_OPERATION: return createFinishingOperation();
      case AfpTextPackage.UP_3I_FINISHING_OPERATION: return createUP3iFinishingOperation();
      case AfpTextPackage.DEVICE_APPEARANCE: return createDeviceAppearance();
      case AfpTextPackage.RESOURCE_OBJECT_INCLUDE: return createResourceObjectInclude();
      case AfpTextPackage.PAGE_OVERLAY_CONDITIONAL_PROCESSING: return createPageOverlayConditionalProcessing();
      case AfpTextPackage.RESOURCE_USAGE_ATTRIBUTE: return createResourceUsageAttribute();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public structuredField createstructuredField()
  {
    structuredFieldImpl structuredField = new structuredFieldImpl();
    return structuredField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LineData createLineData()
  {
    LineDataImpl lineData = new LineDataImpl();
    return lineData;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BAG createBAG()
  {
    BAGImpl bag = new BAGImpl();
    return bag;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BBC createBBC()
  {
    BBCImpl bbc = new BBCImpl();
    return bbc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BCA createBCA()
  {
    BCAImpl bca = new BCAImpl();
    return bca;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BCF createBCF()
  {
    BCFImpl bcf = new BCFImpl();
    return bcf;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BCP createBCP()
  {
    BCPImpl bcp = new BCPImpl();
    return bcp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BDA createBDA()
  {
    BDAImpl bda = new BDAImpl();
    return bda;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BDD createBDD()
  {
    BDDImpl bdd = new BDDImpl();
    return bdd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BDG createBDG()
  {
    BDGImpl bdg = new BDGImpl();
    return bdg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BDI createBDI()
  {
    BDIImpl bdi = new BDIImpl();
    return bdi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BDM createBDM()
  {
    BDMImpl bdm = new BDMImpl();
    return bdm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BDT createBDT()
  {
    BDTImpl bdt = new BDTImpl();
    return bdt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BDX createBDX()
  {
    BDXImpl bdx = new BDXImpl();
    return bdx;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BFG createBFG()
  {
    BFGImpl bfg = new BFGImpl();
    return bfg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BFM createBFM()
  {
    BFMImpl bfm = new BFMImpl();
    return bfm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BFN createBFN()
  {
    BFNImpl bfn = new BFNImpl();
    return bfn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BGR createBGR()
  {
    BGRImpl bgr = new BGRImpl();
    return bgr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BII createBII()
  {
    BIIImpl bii = new BIIImpl();
    return bii;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BIM createBIM()
  {
    BIMImpl bim = new BIMImpl();
    return bim;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BMM createBMM()
  {
    BMMImpl bmm = new BMMImpl();
    return bmm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BMO createBMO()
  {
    BMOImpl bmo = new BMOImpl();
    return bmo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BNG createBNG()
  {
    BNGImpl bng = new BNGImpl();
    return bng;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BOC createBOC()
  {
    BOCImpl boc = new BOCImpl();
    return boc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BOG createBOG()
  {
    BOGImpl bog = new BOGImpl();
    return bog;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BPF createBPF()
  {
    BPFImpl bpf = new BPFImpl();
    return bpf;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BPG createBPG()
  {
    BPGImpl bpg = new BPGImpl();
    return bpg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BPM createBPM()
  {
    BPMImpl bpm = new BPMImpl();
    return bpm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BPS createBPS()
  {
    BPSImpl bps = new BPSImpl();
    return bps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BPT createBPT()
  {
    BPTImpl bpt = new BPTImpl();
    return bpt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BRG createBRG()
  {
    BRGImpl brg = new BRGImpl();
    return brg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BRS createBRS()
  {
    BRSImpl brs = new BRSImpl();
    return brs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BSG createBSG()
  {
    BSGImpl bsg = new BSGImpl();
    return bsg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CAT createCAT()
  {
    CATImpl cat = new CATImpl();
    return cat;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CDD createCDD()
  {
    CDDImpl cdd = new CDDImpl();
    return cdd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CFC createCFC()
  {
    CFCImpl cfc = new CFCImpl();
    return cfc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CFI createCFI()
  {
    CFIImpl cfi = new CFIImpl();
    return cfi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CPC createCPC()
  {
    CPCImpl cpc = new CPCImpl();
    return cpc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CPD createCPD()
  {
    CPDImpl cpd = new CPDImpl();
    return cpd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CPI createCPI()
  {
    CPIImpl cpi = new CPIImpl();
    return cpi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CTC createCTC()
  {
    CTCImpl ctc = new CTCImpl();
    return ctc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DXD createDXD()
  {
    DXDImpl dxd = new DXDImpl();
    return dxd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAG createEAG()
  {
    EAGImpl eag = new EAGImpl();
    return eag;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EBC createEBC()
  {
    EBCImpl ebc = new EBCImpl();
    return ebc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ECA createECA()
  {
    ECAImpl eca = new ECAImpl();
    return eca;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ECF createECF()
  {
    ECFImpl ecf = new ECFImpl();
    return ecf;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ECP createECP()
  {
    ECPImpl ecp = new ECPImpl();
    return ecp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EDG createEDG()
  {
    EDGImpl edg = new EDGImpl();
    return edg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EDI createEDI()
  {
    EDIImpl edi = new EDIImpl();
    return edi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EDM createEDM()
  {
    EDMImpl edm = new EDMImpl();
    return edm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EDT createEDT()
  {
    EDTImpl edt = new EDTImpl();
    return edt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EDX createEDX()
  {
    EDXImpl edx = new EDXImpl();
    return edx;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EFG createEFG()
  {
    EFGImpl efg = new EFGImpl();
    return efg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EFM createEFM()
  {
    EFMImpl efm = new EFMImpl();
    return efm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EFN createEFN()
  {
    EFNImpl efn = new EFNImpl();
    return efn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EGR createEGR()
  {
    EGRImpl egr = new EGRImpl();
    return egr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EII createEII()
  {
    EIIImpl eii = new EIIImpl();
    return eii;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EIM createEIM()
  {
    EIMImpl eim = new EIMImpl();
    return eim;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EMM createEMM()
  {
    EMMImpl emm = new EMMImpl();
    return emm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EMO createEMO()
  {
    EMOImpl emo = new EMOImpl();
    return emo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ENG createENG()
  {
    ENGImpl eng = new ENGImpl();
    return eng;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EOC createEOC()
  {
    EOCImpl eoc = new EOCImpl();
    return eoc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EOG createEOG()
  {
    EOGImpl eog = new EOGImpl();
    return eog;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EPF createEPF()
  {
    EPFImpl epf = new EPFImpl();
    return epf;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EPG createEPG()
  {
    EPGImpl epg = new EPGImpl();
    return epg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EPM createEPM()
  {
    EPMImpl epm = new EPMImpl();
    return epm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EPS createEPS()
  {
    EPSImpl eps = new EPSImpl();
    return eps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EPT createEPT()
  {
    EPTImpl ept = new EPTImpl();
    return ept;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ERG createERG()
  {
    ERGImpl erg = new ERGImpl();
    return erg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ERS createERS()
  {
    ERSImpl ers = new ERSImpl();
    return ers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ESG createESG()
  {
    ESGImpl esg = new ESGImpl();
    return esg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FNC createFNC()
  {
    FNCImpl fnc = new FNCImpl();
    return fnc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FND createFND()
  {
    FNDImpl fnd = new FNDImpl();
    return fnd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FNG createFNG()
  {
    FNGImpl fng = new FNGImpl();
    return fng;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FNI createFNI()
  {
    FNIImpl fni = new FNIImpl();
    return fni;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FNN createFNN()
  {
    FNNImpl fnn = new FNNImpl();
    return fnn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FNM createFNM()
  {
    FNMImpl fnm = new FNMImpl();
    return fnm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FNO createFNO()
  {
    FNOImpl fno = new FNOImpl();
    return fno;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FNP createFNP()
  {
    FNPImpl fnp = new FNPImpl();
    return fnp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GAD createGAD()
  {
    GADImpl gad = new GADImpl();
    return gad;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GDD createGDD()
  {
    GDDImpl gdd = new GDDImpl();
    return gdd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ICP createICP()
  {
    ICPImpl icp = new ICPImpl();
    return icp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IDD createIDD()
  {
    IDDImpl idd = new IDDImpl();
    return idd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IEL createIEL()
  {
    IELImpl iel = new IELImpl();
    return iel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IID createIID()
  {
    IIDImpl iid = new IIDImpl();
    return iid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IMM createIMM()
  {
    IMMImpl imm = new IMMImpl();
    return imm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IOB createIOB()
  {
    IOBImpl iob = new IOBImpl();
    return iob;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IOC createIOC()
  {
    IOCImpl ioc = new IOCImpl();
    return ioc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IPD createIPD()
  {
    IPDImpl ipd = new IPDImpl();
    return ipd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IPG createIPG()
  {
    IPGImpl ipg = new IPGImpl();
    return ipg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IPO createIPO()
  {
    IPOImpl ipo = new IPOImpl();
    return ipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IPS createIPS()
  {
    IPSImpl ips = new IPSImpl();
    return ips;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IRD createIRD()
  {
    IRDImpl ird = new IRDImpl();
    return ird;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LLE createLLE()
  {
    LLEImpl lle = new LLEImpl();
    return lle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LNC createLNC()
  {
    LNCImpl lnc = new LNCImpl();
    return lnc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LND createLND()
  {
    LNDImpl lnd = new LNDImpl();
    return lnd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MBC createMBC()
  {
    MBCImpl mbc = new MBCImpl();
    return mbc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MCA createMCA()
  {
    MCAImpl mca = new MCAImpl();
    return mca;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MCC createMCC()
  {
    MCCImpl mcc = new MCCImpl();
    return mcc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MCD createMCD()
  {
    MCDImpl mcd = new MCDImpl();
    return mcd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MCF createMCF()
  {
    MCFImpl mcf = new MCFImpl();
    return mcf;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MCF1 createMCF1()
  {
    MCF1Impl mcf1 = new MCF1Impl();
    return mcf1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MDD createMDD()
  {
    MDDImpl mdd = new MDDImpl();
    return mdd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MDR createMDR()
  {
    MDRImpl mdr = new MDRImpl();
    return mdr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MFC createMFC()
  {
    MFCImpl mfc = new MFCImpl();
    return mfc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MGO createMGO()
  {
    MGOImpl mgo = new MGOImpl();
    return mgo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MIO createMIO()
  {
    MIOImpl mio = new MIOImpl();
    return mio;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MMC createMMC()
  {
    MMCImpl mmc = new MMCImpl();
    return mmc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MMD createMMD()
  {
    MMDImpl mmd = new MMDImpl();
    return mmd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MMO createMMO()
  {
    MMOImpl mmo = new MMOImpl();
    return mmo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MMT createMMT()
  {
    MMTImpl mmt = new MMTImpl();
    return mmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MPG createMPG()
  {
    MPGImpl mpg = new MPGImpl();
    return mpg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MPO createMPO()
  {
    MPOImpl mpo = new MPOImpl();
    return mpo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MPS createMPS()
  {
    MPSImpl mps = new MPSImpl();
    return mps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MSU createMSU()
  {
    MSUImpl msu = new MSUImpl();
    return msu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NOP createNOP()
  {
    NOPImpl nop = new NOPImpl();
    return nop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OBD createOBD()
  {
    OBDImpl obd = new OBDImpl();
    return obd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OBP createOBP()
  {
    OBPImpl obp = new OBPImpl();
    return obp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OCD createOCD()
  {
    OCDImpl ocd = new OCDImpl();
    return ocd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PEC createPEC()
  {
    PECImpl pec = new PECImpl();
    return pec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PFC createPFC()
  {
    PFCImpl pfc = new PFCImpl();
    return pfc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PGD createPGD()
  {
    PGDImpl pgd = new PGDImpl();
    return pgd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PGP createPGP()
  {
    PGPImpl pgp = new PGPImpl();
    return pgp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PGP1 createPGP1()
  {
    PGP1Impl pgp1 = new PGP1Impl();
    return pgp1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PMC createPMC()
  {
    PMCImpl pmc = new PMCImpl();
    return pmc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PPO createPPO()
  {
    PPOImpl ppo = new PPOImpl();
    return ppo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PTD createPTD()
  {
    PTDImpl ptd = new PTDImpl();
    return ptd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PTD1 createPTD1()
  {
    PTD1Impl ptd1 = new PTD1Impl();
    return ptd1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PTX createPTX()
  {
    PTXImpl ptx = new PTXImpl();
    return ptx;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TLE createTLE()
  {
    TLEImpl tle = new TLEImpl();
    return tle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FGD createFGD()
  {
    FGDImpl fgd = new FGDImpl();
    return fgd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CPIRG createCPIRG()
  {
    CPIRGImpl cpirg = new CPIRGImpl();
    return cpirg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CFIRG createCFIRG()
  {
    CFIRGImpl cfirg = new CFIRGImpl();
    return cfirg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FNIRG createFNIRG()
  {
    FNIRGImpl fnirg = new FNIRGImpl();
    return fnirg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FNMRG createFNMRG()
  {
    FNMRGImpl fnmrg = new FNMRGImpl();
    return fnmrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LLERG createLLERG()
  {
    LLERGImpl llerg = new LLERGImpl();
    return llerg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MPSRG createMPSRG()
  {
    MPSRGImpl mpsrg = new MPSRGImpl();
    return mpsrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MCFRG createMCFRG()
  {
    MCFRGImpl mcfrg = new MCFRGImpl();
    return mcfrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MBCRG createMBCRG()
  {
    MBCRGImpl mbcrg = new MBCRGImpl();
    return mbcrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MCARG createMCARG()
  {
    MCARGImpl mcarg = new MCARGImpl();
    return mcarg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MCDRG createMCDRG()
  {
    MCDRGImpl mcdrg = new MCDRGImpl();
    return mcdrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MDRRG createMDRRG()
  {
    MDRRGImpl mdrrg = new MDRRGImpl();
    return mdrrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MGORG createMGORG()
  {
    MGORGImpl mgorg = new MGORGImpl();
    return mgorg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MIORG createMIORG()
  {
    MIORGImpl miorg = new MIORGImpl();
    return miorg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MMDRG createMMDRG()
  {
    MMDRGImpl mmdrg = new MMDRGImpl();
    return mmdrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MMTRG createMMTRG()
  {
    MMTRGImpl mmtrg = new MMTRGImpl();
    return mmtrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MPGRG createMPGRG()
  {
    MPGRGImpl mpgrg = new MPGRGImpl();
    return mpgrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MPORG createMPORG()
  {
    MPORGImpl mporg = new MPORGImpl();
    return mporg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PPORG createPPORG()
  {
    PPORGImpl pporg = new PPORGImpl();
    return pporg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PGPRG createPGPRG()
  {
    PGPRGImpl pgprg = new PGPRGImpl();
    return pgprg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MCCRG createMCCRG()
  {
    MCCRGImpl mccrg = new MCCRGImpl();
    return mccrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MMORG createMMORG()
  {
    MMORGImpl mmorg = new MMORGImpl();
    return mmorg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BandImageRG createBandImageRG()
  {
    BandImageRGImpl bandImageRG = new BandImageRGImpl();
    return bandImageRG;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MCF1RG createMCF1RG()
  {
    MCF1RGImpl mcf1RG = new MCF1RGImpl();
    return mcf1RG;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MMCRG createMMCRG()
  {
    MMCRGImpl mmcrg = new MMCRGImpl();
    return mmcrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FNORG createFNORG()
  {
    FNORGImpl fnorg = new FNORGImpl();
    return fnorg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FNPRG createFNPRG()
  {
    FNPRGImpl fnprg = new FNPRGImpl();
    return fnprg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TileTOCRG createTileTOCRG()
  {
    TileTOCRGImpl tileTOCRG = new TileTOCRGImpl();
    return tileTOCRG;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SamplingRatiosRG createSamplingRatiosRG()
  {
    SamplingRatiosRGImpl samplingRatiosRG = new SamplingRatiosRGImpl();
    return samplingRatiosRG;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExternalAlgorithmRG createExternalAlgorithmRG()
  {
    ExternalAlgorithmRGImpl externalAlgorithmRG = new ExternalAlgorithmRGImpl();
    return externalAlgorithmRG;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FNNRG createFNNRG()
  {
    FNNRGImpl fnnrg = new FNNRGImpl();
    return fnnrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCBEZRG createGCBEZRG()
  {
    GCBEZRGImpl gcbezrg = new GCBEZRGImpl();
    return gcbezrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCCBEZRG createGCCBEZRG()
  {
    GCCBEZRGImpl gccbezrg = new GCCBEZRGImpl();
    return gccbezrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GFLTRG createGFLTRG()
  {
    GFLTRGImpl gfltrg = new GFLTRGImpl();
    return gfltrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCFLTRG createGCFLTRG()
  {
    GCFLTRGImpl gcfltrg = new GCFLTRGImpl();
    return gcfltrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GLINERG createGLINERG()
  {
    GLINERGImpl glinerg = new GLINERGImpl();
    return glinerg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCLINERG createGCLINERG()
  {
    GCLINERGImpl gclinerg = new GCLINERGImpl();
    return gclinerg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GMRKRG createGMRKRG()
  {
    GMRKRGImpl gmrkrg = new GMRKRGImpl();
    return gmrkrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCMRKRG createGCMRKRG()
  {
    GCMRKRGImpl gcmrkrg = new GCMRKRGImpl();
    return gcmrkrg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GRLINERG createGRLINERG()
  {
    GRLINERGImpl grlinerg = new GRLINERGImpl();
    return grlinerg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCRLINERG createGCRLINERG()
  {
    GCRLINERGImpl gcrlinerg = new GCRLINERGImpl();
    return gcrlinerg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MSURG createMSURG()
  {
    MSURGImpl msurg = new MSURGImpl();
    return msurg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public triplet createtriplet()
  {
    tripletImpl triplet = new tripletImpl();
    return triplet;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AMB createAMB()
  {
    AMBImpl amb = new AMBImpl();
    return amb;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AMI createAMI()
  {
    AMIImpl ami = new AMIImpl();
    return ami;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BLN createBLN()
  {
    BLNImpl bln = new BLNImpl();
    return bln;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BSU createBSU()
  {
    BSUImpl bsu = new BSUImpl();
    return bsu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DBR createDBR()
  {
    DBRImpl dbr = new DBRImpl();
    return dbr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DIR createDIR()
  {
    DIRImpl dir = new DIRImpl();
    return dir;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ESU createESU()
  {
    ESUImpl esu = new ESUImpl();
    return esu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NOPCS createNOPCS()
  {
    NOPCSImpl nopcs = new NOPCSImpl();
    return nopcs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OVS createOVS()
  {
    OVSImpl ovs = new OVSImpl();
    return ovs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RMB createRMB()
  {
    RMBImpl rmb = new RMBImpl();
    return rmb;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RMI createRMI()
  {
    RMIImpl rmi = new RMIImpl();
    return rmi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RPS createRPS()
  {
    RPSImpl rps = new RPSImpl();
    return rps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SBI createSBI()
  {
    SBIImpl sbi = new SBIImpl();
    return sbi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SCFL createSCFL()
  {
    SCFLImpl scfl = new SCFLImpl();
    return scfl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SEC createSEC()
  {
    SECImpl sec = new SECImpl();
    return sec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SIA createSIA()
  {
    SIAImpl sia = new SIAImpl();
    return sia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SIM createSIM()
  {
    SIMImpl sim = new SIMImpl();
    return sim;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public STC createSTC()
  {
    STCImpl stc = new STCImpl();
    return stc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public STO createSTO()
  {
    STOImpl sto = new STOImpl();
    return sto;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SVI createSVI()
  {
    SVIImpl svi = new SVIImpl();
    return svi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TBM createTBM()
  {
    TBMImpl tbm = new TBMImpl();
    return tbm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TRN createTRN()
  {
    TRNImpl trn = new TRNImpl();
    return trn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public USC createUSC()
  {
    USCImpl usc = new USCImpl();
    return usc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AttributeQualifier createAttributeQualifier()
  {
    AttributeQualifierImpl attributeQualifier = new AttributeQualifierImpl();
    return attributeQualifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AttributeValue createAttributeValue()
  {
    AttributeValueImpl attributeValue = new AttributeValueImpl();
    return attributeValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CGCSGID createCGCSGID()
  {
    CGCSGIDImpl cgcsgid = new CGCSGIDImpl();
    return cgcsgid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CRCResourceManagement createCRCResourceManagement()
  {
    CRCResourceManagementImpl crcResourceManagement = new CRCResourceManagementImpl();
    return crcResourceManagement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CharacterRotation createCharacterRotation()
  {
    CharacterRotationImpl characterRotation = new CharacterRotationImpl();
    return characterRotation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ColorSpecification createColorSpecification()
  {
    ColorSpecificationImpl colorSpecification = new ColorSpecificationImpl();
    return colorSpecification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Comment createComment()
  {
    CommentImpl comment = new CommentImpl();
    return comment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataObjectFontDescriptor createDataObjectFontDescriptor()
  {
    DataObjectFontDescriptorImpl dataObjectFontDescriptor = new DataObjectFontDescriptorImpl();
    return dataObjectFontDescriptor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DescriptorPosition createDescriptorPosition()
  {
    DescriptorPositionImpl descriptorPosition = new DescriptorPositionImpl();
    return descriptorPosition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EncodingSchemeID createEncodingSchemeID()
  {
    EncodingSchemeIDImpl encodingSchemeID = new EncodingSchemeIDImpl();
    return encodingSchemeID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FontResolution createFontResolution()
  {
    FontResolutionImpl fontResolution = new FontResolutionImpl();
    return fontResolution;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FullyQualifiedName createFullyQualifiedName()
  {
    FullyQualifiedNameImpl fullyQualifiedName = new FullyQualifiedNameImpl();
    return fullyQualifiedName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LocalDateAndTimeStamp createLocalDateAndTimeStamp()
  {
    LocalDateAndTimeStampImpl localDateAndTimeStamp = new LocalDateAndTimeStampImpl();
    return localDateAndTimeStamp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UniversalDateAndTimeStamp createUniversalDateAndTimeStamp()
  {
    UniversalDateAndTimeStampImpl universalDateAndTimeStamp = new UniversalDateAndTimeStampImpl();
    return universalDateAndTimeStamp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MappingOption createMappingOption()
  {
    MappingOptionImpl mappingOption = new MappingOptionImpl();
    return mappingOption;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MediaEjectControl createMediaEjectControl()
  {
    MediaEjectControlImpl mediaEjectControl = new MediaEjectControlImpl();
    return mediaEjectControl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MediumMapPageNumber createMediumMapPageNumber()
  {
    MediumMapPageNumberImpl mediumMapPageNumber = new MediumMapPageNumberImpl();
    return mediumMapPageNumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MediumOrientation createMediumOrientation()
  {
    MediumOrientationImpl mediumOrientation = new MediumOrientationImpl();
    return mediumOrientation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MeasurementUnits createMeasurementUnits()
  {
    MeasurementUnitsImpl measurementUnits = new MeasurementUnitsImpl();
    return measurementUnits;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MODCAInterchangeSet createMODCAInterchangeSet()
  {
    MODCAInterchangeSetImpl modcaInterchangeSet = new MODCAInterchangeSetImpl();
    return modcaInterchangeSet;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ObjectAreaSize createObjectAreaSize()
  {
    ObjectAreaSizeImpl objectAreaSize = new ObjectAreaSizeImpl();
    return objectAreaSize;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ObjectClassification createObjectClassification()
  {
    ObjectClassificationImpl objectClassification = new ObjectClassificationImpl();
    return objectClassification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ObjectFunctionSetSpecification createObjectFunctionSetSpecification()
  {
    ObjectFunctionSetSpecificationImpl objectFunctionSetSpecification = new ObjectFunctionSetSpecificationImpl();
    return objectFunctionSetSpecification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ObjectOffset createObjectOffset()
  {
    ObjectOffsetImpl objectOffset = new ObjectOffsetImpl();
    return objectOffset;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ResourceObjectType createResourceObjectType()
  {
    ResourceObjectTypeImpl resourceObjectType = new ResourceObjectTypeImpl();
    return resourceObjectType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PagePositionInformation createPagePositionInformation()
  {
    PagePositionInformationImpl pagePositionInformation = new PagePositionInformationImpl();
    return pagePositionInformation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PresentationControl createPresentationControl()
  {
    PresentationControlImpl presentationControl = new PresentationControlImpl();
    return presentationControl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PresentationSpaceResetMixing createPresentationSpaceResetMixing()
  {
    PresentationSpaceResetMixingImpl presentationSpaceResetMixing = new PresentationSpaceResetMixingImpl();
    return presentationSpaceResetMixing;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PresentationSpaceMixingRules createPresentationSpaceMixingRules()
  {
    PresentationSpaceMixingRulesImpl presentationSpaceMixingRules = new PresentationSpaceMixingRulesImpl();
    return presentationSpaceMixingRules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ResourceLocalIdentifier createResourceLocalIdentifier()
  {
    ResourceLocalIdentifierImpl resourceLocalIdentifier = new ResourceLocalIdentifierImpl();
    return resourceLocalIdentifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ResourceSectionNumber createResourceSectionNumber()
  {
    ResourceSectionNumberImpl resourceSectionNumber = new ResourceSectionNumberImpl();
    return resourceSectionNumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TextOrientation createTextOrientation()
  {
    TextOrientationImpl textOrientation = new TextOrientationImpl();
    return textOrientation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FontHorizontalScaleFactor createFontHorizontalScaleFactor()
  {
    FontHorizontalScaleFactorImpl fontHorizontalScaleFactor = new FontHorizontalScaleFactorImpl();
    return fontHorizontalScaleFactor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FontDescriptorSpecification createFontDescriptorSpecification()
  {
    FontDescriptorSpecificationImpl fontDescriptorSpecification = new FontDescriptorSpecificationImpl();
    return fontDescriptorSpecification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BeginSegment createBeginSegment()
  {
    BeginSegmentImpl beginSegment = new BeginSegmentImpl();
    return beginSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EndSegment createEndSegment()
  {
    EndSegmentImpl endSegment = new EndSegmentImpl();
    return endSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BeginTile createBeginTile()
  {
    BeginTileImpl beginTile = new BeginTileImpl();
    return beginTile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EndTile createEndTile()
  {
    EndTileImpl endTile = new EndTileImpl();
    return endTile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BeginTransparencyMask createBeginTransparencyMask()
  {
    BeginTransparencyMaskImpl beginTransparencyMask = new BeginTransparencyMaskImpl();
    return beginTransparencyMask;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EndTransparencyMask createEndTransparencyMask()
  {
    EndTransparencyMaskImpl endTransparencyMask = new EndTransparencyMaskImpl();
    return endTransparencyMask;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BeginImage createBeginImage()
  {
    BeginImageImpl beginImage = new BeginImageImpl();
    return beginImage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EndImage createEndImage()
  {
    EndImageImpl endImage = new EndImageImpl();
    return endImage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ImageSize createImageSize()
  {
    ImageSizeImpl imageSize = new ImageSizeImpl();
    return imageSize;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ImageEncoding createImageEncoding()
  {
    ImageEncodingImpl imageEncoding = new ImageEncodingImpl();
    return imageEncoding;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IDESize createIDESize()
  {
    IDESizeImpl ideSize = new IDESizeImpl();
    return ideSize;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ImageLUTID createImageLUTID()
  {
    ImageLUTIDImpl imageLUTID = new ImageLUTIDImpl();
    return imageLUTID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BandImage createBandImage()
  {
    BandImageImpl bandImage = new BandImageImpl();
    return bandImage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IDEStructure createIDEStructure()
  {
    IDEStructureImpl ideStructure = new IDEStructureImpl();
    return ideStructure;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExternalAlgorithm createExternalAlgorithm()
  {
    ExternalAlgorithmImpl externalAlgorithm = new ExternalAlgorithmImpl();
    return externalAlgorithm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TilePosition createTilePosition()
  {
    TilePositionImpl tilePosition = new TilePositionImpl();
    return tilePosition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TileSize createTileSize()
  {
    TileSizeImpl tileSize = new TileSizeImpl();
    return tileSize;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TileSetColor createTileSetColor()
  {
    TileSetColorImpl tileSetColor = new TileSetColorImpl();
    return tileSetColor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SetBiLevelImageColor createSetBiLevelImageColor()
  {
    SetBiLevelImageColorImpl setBiLevelImageColor = new SetBiLevelImageColorImpl();
    return setBiLevelImageColor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IOCAFunctionSetIdentification createIOCAFunctionSetIdentification()
  {
    IOCAFunctionSetIdentificationImpl iocaFunctionSetIdentification = new IOCAFunctionSetIdentificationImpl();
    return iocaFunctionSetIdentification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ImageData createImageData()
  {
    ImageDataImpl imageData = new ImageDataImpl();
    return imageData;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BandImageData createBandImageData()
  {
    BandImageDataImpl bandImageData = new BandImageDataImpl();
    return bandImageData;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IncludeTile createIncludeTile()
  {
    IncludeTileImpl includeTile = new IncludeTileImpl();
    return includeTile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ImageSubsampling createImageSubsampling()
  {
    ImageSubsamplingImpl imageSubsampling = new ImageSubsamplingImpl();
    return imageSubsampling;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SamplingRatios createSamplingRatios()
  {
    SamplingRatiosImpl samplingRatios = new SamplingRatiosImpl();
    return samplingRatios;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TileTOC createTileTOC()
  {
    TileTOCImpl tileTOC = new TileTOCImpl();
    return tileTOC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FNNRG2 createFNNRG2()
  {
    FNNRG2Impl fnnrg2 = new FNNRG2Impl();
    return fnnrg2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BeginSegmentCommand createBeginSegmentCommand()
  {
    BeginSegmentCommandImpl beginSegmentCommand = new BeginSegmentCommandImpl();
    return beginSegmentCommand;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EndSegmentCommand createEndSegmentCommand()
  {
    EndSegmentCommandImpl endSegmentCommand = new EndSegmentCommandImpl();
    return endSegmentCommand;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GBAR createGBAR()
  {
    GBARImpl gbar = new GBARImpl();
    return gbar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GBIMG createGBIMG()
  {
    GBIMGImpl gbimg = new GBIMGImpl();
    return gbimg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCBIMG createGCBIMG()
  {
    GCBIMGImpl gcbimg = new GCBIMGImpl();
    return gcbimg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GBOX createGBOX()
  {
    GBOXImpl gbox = new GBOXImpl();
    return gbox;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCBOX createGCBOX()
  {
    GCBOXImpl gcbox = new GCBOXImpl();
    return gcbox;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCHST createGCHST()
  {
    GCHSTImpl gchst = new GCHSTImpl();
    return gchst;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCCHST createGCCHST()
  {
    GCCHSTImpl gcchst = new GCCHSTImpl();
    return gcchst;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCOMT createGCOMT()
  {
    GCOMTImpl gcomt = new GCOMTImpl();
    return gcomt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GEAR createGEAR()
  {
    GEARImpl gear = new GEARImpl();
    return gear;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GEIMG createGEIMG()
  {
    GEIMGImpl geimg = new GEIMGImpl();
    return geimg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GEPROL createGEPROL()
  {
    GEPROLImpl geprol = new GEPROLImpl();
    return geprol;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GFLT createGFLT()
  {
    GFLTImpl gflt = new GFLTImpl();
    return gflt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCFLT createGCFLT()
  {
    GCFLTImpl gcflt = new GCFLTImpl();
    return gcflt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GFARC createGFARC()
  {
    GFARCImpl gfarc = new GFARCImpl();
    return gfarc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCFARC createGCFARC()
  {
    GCFARCImpl gcfarc = new GCFARCImpl();
    return gcfarc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GIMD createGIMD()
  {
    GIMDImpl gimd = new GIMDImpl();
    return gimd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GLINE createGLINE()
  {
    GLINEImpl gline = new GLINEImpl();
    return gline;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCLINE createGCLINE()
  {
    GCLINEImpl gcline = new GCLINEImpl();
    return gcline;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GMRK createGMRK()
  {
    GMRKImpl gmrk = new GMRKImpl();
    return gmrk;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCMRK createGCMRK()
  {
    GCMRKImpl gcmrk = new GCMRKImpl();
    return gcmrk;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GNOP1 createGNOP1()
  {
    GNOP1Impl gnop1 = new GNOP1Impl();
    return gnop1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GPARC createGPARC()
  {
    GPARCImpl gparc = new GPARCImpl();
    return gparc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCPARC createGCPARC()
  {
    GCPARCImpl gcparc = new GCPARCImpl();
    return gcparc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GRLINE createGRLINE()
  {
    GRLINEImpl grline = new GRLINEImpl();
    return grline;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCRLINE createGCRLINE()
  {
    GCRLINEImpl gcrline = new GCRLINEImpl();
    return gcrline;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSGCH createGSGCH()
  {
    GSGCHImpl gsgch = new GSGCHImpl();
    return gsgch;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSAP createGSAP()
  {
    GSAPImpl gsap = new GSAPImpl();
    return gsap;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSBMX createGSBMX()
  {
    GSBMXImpl gsbmx = new GSBMXImpl();
    return gsbmx;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSCA createGSCA()
  {
    GSCAImpl gsca = new GSCAImpl();
    return gsca;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSCC createGSCC()
  {
    GSCCImpl gscc = new GSCCImpl();
    return gscc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSCD createGSCD()
  {
    GSCDImpl gscd = new GSCDImpl();
    return gscd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSCR createGSCR()
  {
    GSCRImpl gscr = new GSCRImpl();
    return gscr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSCS createGSCS()
  {
    GSCSImpl gscs = new GSCSImpl();
    return gscs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSCH createGSCH()
  {
    GSCHImpl gsch = new GSCHImpl();
    return gsch;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSCOL createGSCOL()
  {
    GSCOLImpl gscol = new GSCOLImpl();
    return gscol;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSCP createGSCP()
  {
    GSCPImpl gscp = new GSCPImpl();
    return gscp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSECOL createGSECOL()
  {
    GSECOLImpl gsecol = new GSECOLImpl();
    return gsecol;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSFLW createGSFLW()
  {
    GSFLWImpl gsflw = new GSFLWImpl();
    return gsflw;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSLT createGSLT()
  {
    GSLTImpl gslt = new GSLTImpl();
    return gslt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSLW createGSLW()
  {
    GSLWImpl gslw = new GSLWImpl();
    return gslw;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSMC createGSMC()
  {
    GSMCImpl gsmc = new GSMCImpl();
    return gsmc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSMP createGSMP()
  {
    GSMPImpl gsmp = new GSMPImpl();
    return gsmp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSMS createGSMS()
  {
    GSMSImpl gsms = new GSMSImpl();
    return gsms;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSMT createGSMT()
  {
    GSMTImpl gsmt = new GSMTImpl();
    return gsmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSMX createGSMX()
  {
    GSMXImpl gsmx = new GSMXImpl();
    return gsmx;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSPS createGSPS()
  {
    GSPSImpl gsps = new GSPSImpl();
    return gsps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSPT createGSPT()
  {
    GSPTImpl gspt = new GSPTImpl();
    return gspt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSPCOL createGSPCOL()
  {
    GSPCOLImpl gspcol = new GSPCOLImpl();
    return gspcol;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSLE createGSLE()
  {
    GSLEImpl gsle = new GSLEImpl();
    return gsle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GSLJ createGSLJ()
  {
    GSLJImpl gslj = new GSLJImpl();
    return gslj;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCBEZ createGCBEZ()
  {
    GCBEZImpl gcbez = new GCBEZImpl();
    return gcbez;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GCCBEZ createGCCBEZ()
  {
    GCCBEZImpl gccbez = new GCCBEZImpl();
    return gccbez;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WindowSpecification createWindowSpecification()
  {
    WindowSpecificationImpl windowSpecification = new WindowSpecificationImpl();
    return windowSpecification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DrawingOrderSubset createDrawingOrderSubset()
  {
    DrawingOrderSubsetImpl drawingOrderSubset = new DrawingOrderSubsetImpl();
    return drawingOrderSubset;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TonerSaver createTonerSaver()
  {
    TonerSaverImpl tonerSaver = new TonerSaverImpl();
    return tonerSaver;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ColorFidelity createColorFidelity()
  {
    ColorFidelityImpl colorFidelity = new ColorFidelityImpl();
    return colorFidelity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FontFidelity createFontFidelity()
  {
    FontFidelityImpl fontFidelity = new FontFidelityImpl();
    return fontFidelity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TextFidelity createTextFidelity()
  {
    TextFidelityImpl textFidelity = new TextFidelityImpl();
    return textFidelity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MediaFidelity createMediaFidelity()
  {
    MediaFidelityImpl mediaFidelity = new MediaFidelityImpl();
    return mediaFidelity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FinishingFidelity createFinishingFidelity()
  {
    FinishingFidelityImpl finishingFidelity = new FinishingFidelityImpl();
    return finishingFidelity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CMRFidelity createCMRFidelity()
  {
    CMRFidelityImpl cmrFidelity = new CMRFidelityImpl();
    return cmrFidelity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ObjectByteExtent createObjectByteExtent()
  {
    ObjectByteExtentImpl objectByteExtent = new ObjectByteExtentImpl();
    return objectByteExtent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ObjectByteOffset createObjectByteOffset()
  {
    ObjectByteOffsetImpl objectByteOffset = new ObjectByteOffsetImpl();
    return objectByteOffset;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ObjectStructuredFieldExtent createObjectStructuredFieldExtent()
  {
    ObjectStructuredFieldExtentImpl objectStructuredFieldExtent = new ObjectStructuredFieldExtentImpl();
    return objectStructuredFieldExtent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ObjectStructuredFieldOffset createObjectStructuredFieldOffset()
  {
    ObjectStructuredFieldOffsetImpl objectStructuredFieldOffset = new ObjectStructuredFieldOffsetImpl();
    return objectStructuredFieldOffset;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ObjectCount createObjectCount()
  {
    ObjectCountImpl objectCount = new ObjectCountImpl();
    return objectCount;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ObjectOriginIdentifier createObjectOriginIdentifier()
  {
    ObjectOriginIdentifierImpl objectOriginIdentifier = new ObjectOriginIdentifierImpl();
    return objectOriginIdentifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LineDataObjectPositionMigration createLineDataObjectPositionMigration()
  {
    LineDataObjectPositionMigrationImpl lineDataObjectPositionMigration = new LineDataObjectPositionMigrationImpl();
    return lineDataObjectPositionMigration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ColorManagementResourceDescriptor createColorManagementResourceDescriptor()
  {
    ColorManagementResourceDescriptorImpl colorManagementResourceDescriptor = new ColorManagementResourceDescriptorImpl();
    return colorManagementResourceDescriptor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ImageResolution createImageResolution()
  {
    ImageResolutionImpl imageResolution = new ImageResolutionImpl();
    return imageResolution;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ObjectContainerPresentationSpaceSize createObjectContainerPresentationSpaceSize()
  {
    ObjectContainerPresentationSpaceSizeImpl objectContainerPresentationSpaceSize = new ObjectContainerPresentationSpaceSizeImpl();
    return objectContainerPresentationSpaceSize;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExtendedResourceLocalIdentifier createExtendedResourceLocalIdentifier()
  {
    ExtendedResourceLocalIdentifierImpl extendedResourceLocalIdentifier = new ExtendedResourceLocalIdentifierImpl();
    return extendedResourceLocalIdentifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MetricAdjustment createMetricAdjustment()
  {
    MetricAdjustmentImpl metricAdjustment = new MetricAdjustmentImpl();
    return metricAdjustment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExtensionFont createExtensionFont()
  {
    ExtensionFontImpl extensionFont = new ExtensionFontImpl();
    return extensionFont;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RenderingIntent createRenderingIntent()
  {
    RenderingIntentImpl renderingIntent = new RenderingIntentImpl();
    return renderingIntent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FontCodedGraphicCharacterSetGlobalIdentifier createFontCodedGraphicCharacterSetGlobalIdentifier()
  {
    FontCodedGraphicCharacterSetGlobalIdentifierImpl fontCodedGraphicCharacterSetGlobalIdentifier = new FontCodedGraphicCharacterSetGlobalIdentifierImpl();
    return fontCodedGraphicCharacterSetGlobalIdentifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LocaleSelector createLocaleSelector()
  {
    LocaleSelectorImpl localeSelector = new LocaleSelectorImpl();
    return localeSelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FinishingOperation createFinishingOperation()
  {
    FinishingOperationImpl finishingOperation = new FinishingOperationImpl();
    return finishingOperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UP3iFinishingOperation createUP3iFinishingOperation()
  {
    UP3iFinishingOperationImpl up3iFinishingOperation = new UP3iFinishingOperationImpl();
    return up3iFinishingOperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DeviceAppearance createDeviceAppearance()
  {
    DeviceAppearanceImpl deviceAppearance = new DeviceAppearanceImpl();
    return deviceAppearance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ResourceObjectInclude createResourceObjectInclude()
  {
    ResourceObjectIncludeImpl resourceObjectInclude = new ResourceObjectIncludeImpl();
    return resourceObjectInclude;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PageOverlayConditionalProcessing createPageOverlayConditionalProcessing()
  {
    PageOverlayConditionalProcessingImpl pageOverlayConditionalProcessing = new PageOverlayConditionalProcessingImpl();
    return pageOverlayConditionalProcessing;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ResourceUsageAttribute createResourceUsageAttribute()
  {
    ResourceUsageAttributeImpl resourceUsageAttribute = new ResourceUsageAttributeImpl();
    return resourceUsageAttribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AfpTextPackage getAfpTextPackage()
  {
    return (AfpTextPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static AfpTextPackage getPackage()
  {
    return AfpTextPackage.eINSTANCE;
  }

} //AfpTextFactoryImpl
