/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText.impl;

import org.afplib.afpText.AfpTextPackage;
import org.afplib.afpText.GCBOX;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>GCBOX</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.impl.GCBOXImpl#getRES <em>RES</em>}</li>
 *   <li>{@link org.afplib.afpText.impl.GCBOXImpl#getXPOS1 <em>XPOS1</em>}</li>
 *   <li>{@link org.afplib.afpText.impl.GCBOXImpl#getYPOS1 <em>YPOS1</em>}</li>
 *   <li>{@link org.afplib.afpText.impl.GCBOXImpl#getHAXIS <em>HAXIS</em>}</li>
 *   <li>{@link org.afplib.afpText.impl.GCBOXImpl#getVAXIS <em>VAXIS</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GCBOXImpl extends tripletImpl implements GCBOX
{
  /**
   * The default value of the '{@link #getRES() <em>RES</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRES()
   * @generated
   * @ordered
   */
  protected static final int RES_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getRES() <em>RES</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRES()
   * @generated
   * @ordered
   */
  protected int res = RES_EDEFAULT;

  /**
   * The default value of the '{@link #getXPOS1() <em>XPOS1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getXPOS1()
   * @generated
   * @ordered
   */
  protected static final int XPOS1_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getXPOS1() <em>XPOS1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getXPOS1()
   * @generated
   * @ordered
   */
  protected int xpos1 = XPOS1_EDEFAULT;

  /**
   * The default value of the '{@link #getYPOS1() <em>YPOS1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getYPOS1()
   * @generated
   * @ordered
   */
  protected static final int YPOS1_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getYPOS1() <em>YPOS1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getYPOS1()
   * @generated
   * @ordered
   */
  protected int ypos1 = YPOS1_EDEFAULT;

  /**
   * The default value of the '{@link #getHAXIS() <em>HAXIS</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHAXIS()
   * @generated
   * @ordered
   */
  protected static final int HAXIS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getHAXIS() <em>HAXIS</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHAXIS()
   * @generated
   * @ordered
   */
  protected int haxis = HAXIS_EDEFAULT;

  /**
   * The default value of the '{@link #getVAXIS() <em>VAXIS</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVAXIS()
   * @generated
   * @ordered
   */
  protected static final int VAXIS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getVAXIS() <em>VAXIS</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVAXIS()
   * @generated
   * @ordered
   */
  protected int vaxis = VAXIS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GCBOXImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AfpTextPackage.eINSTANCE.getGCBOX();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getRES()
  {
    return res;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRES(int newRES)
  {
    int oldRES = res;
    res = newRES;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AfpTextPackage.GCBOX__RES, oldRES, res));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getXPOS1()
  {
    return xpos1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setXPOS1(int newXPOS1)
  {
    int oldXPOS1 = xpos1;
    xpos1 = newXPOS1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AfpTextPackage.GCBOX__XPOS1, oldXPOS1, xpos1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getYPOS1()
  {
    return ypos1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setYPOS1(int newYPOS1)
  {
    int oldYPOS1 = ypos1;
    ypos1 = newYPOS1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AfpTextPackage.GCBOX__YPOS1, oldYPOS1, ypos1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getHAXIS()
  {
    return haxis;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHAXIS(int newHAXIS)
  {
    int oldHAXIS = haxis;
    haxis = newHAXIS;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AfpTextPackage.GCBOX__HAXIS, oldHAXIS, haxis));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getVAXIS()
  {
    return vaxis;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVAXIS(int newVAXIS)
  {
    int oldVAXIS = vaxis;
    vaxis = newVAXIS;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AfpTextPackage.GCBOX__VAXIS, oldVAXIS, vaxis));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AfpTextPackage.GCBOX__RES:
        return getRES();
      case AfpTextPackage.GCBOX__XPOS1:
        return getXPOS1();
      case AfpTextPackage.GCBOX__YPOS1:
        return getYPOS1();
      case AfpTextPackage.GCBOX__HAXIS:
        return getHAXIS();
      case AfpTextPackage.GCBOX__VAXIS:
        return getVAXIS();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AfpTextPackage.GCBOX__RES:
        setRES((Integer)newValue);
        return;
      case AfpTextPackage.GCBOX__XPOS1:
        setXPOS1((Integer)newValue);
        return;
      case AfpTextPackage.GCBOX__YPOS1:
        setYPOS1((Integer)newValue);
        return;
      case AfpTextPackage.GCBOX__HAXIS:
        setHAXIS((Integer)newValue);
        return;
      case AfpTextPackage.GCBOX__VAXIS:
        setVAXIS((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AfpTextPackage.GCBOX__RES:
        setRES(RES_EDEFAULT);
        return;
      case AfpTextPackage.GCBOX__XPOS1:
        setXPOS1(XPOS1_EDEFAULT);
        return;
      case AfpTextPackage.GCBOX__YPOS1:
        setYPOS1(YPOS1_EDEFAULT);
        return;
      case AfpTextPackage.GCBOX__HAXIS:
        setHAXIS(HAXIS_EDEFAULT);
        return;
      case AfpTextPackage.GCBOX__VAXIS:
        setVAXIS(VAXIS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AfpTextPackage.GCBOX__RES:
        return res != RES_EDEFAULT;
      case AfpTextPackage.GCBOX__XPOS1:
        return xpos1 != XPOS1_EDEFAULT;
      case AfpTextPackage.GCBOX__YPOS1:
        return ypos1 != YPOS1_EDEFAULT;
      case AfpTextPackage.GCBOX__HAXIS:
        return haxis != HAXIS_EDEFAULT;
      case AfpTextPackage.GCBOX__VAXIS:
        return vaxis != VAXIS_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (RES: ");
    result.append(res);
    result.append(", XPOS1: ");
    result.append(xpos1);
    result.append(", YPOS1: ");
    result.append(ypos1);
    result.append(", HAXIS: ");
    result.append(haxis);
    result.append(", VAXIS: ");
    result.append(vaxis);
    result.append(')');
    return result.toString();
  }

} //GCBOXImpl
