/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText.impl;

import org.afplib.afpText.AfpTextPackage;
import org.afplib.afpText.ObjectByteExtent;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Object Byte Extent</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.impl.ObjectByteExtentImpl#getByteExt <em>Byte Ext</em>}</li>
 *   <li>{@link org.afplib.afpText.impl.ObjectByteExtentImpl#getByteExtHi <em>Byte Ext Hi</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ObjectByteExtentImpl extends tripletImpl implements ObjectByteExtent
{
  /**
   * The default value of the '{@link #getByteExt() <em>Byte Ext</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getByteExt()
   * @generated
   * @ordered
   */
  protected static final int BYTE_EXT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getByteExt() <em>Byte Ext</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getByteExt()
   * @generated
   * @ordered
   */
  protected int byteExt = BYTE_EXT_EDEFAULT;

  /**
   * The default value of the '{@link #getByteExtHi() <em>Byte Ext Hi</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getByteExtHi()
   * @generated
   * @ordered
   */
  protected static final int BYTE_EXT_HI_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getByteExtHi() <em>Byte Ext Hi</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getByteExtHi()
   * @generated
   * @ordered
   */
  protected int byteExtHi = BYTE_EXT_HI_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ObjectByteExtentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AfpTextPackage.eINSTANCE.getObjectByteExtent();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getByteExt()
  {
    return byteExt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setByteExt(int newByteExt)
  {
    int oldByteExt = byteExt;
    byteExt = newByteExt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AfpTextPackage.OBJECT_BYTE_EXTENT__BYTE_EXT, oldByteExt, byteExt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getByteExtHi()
  {
    return byteExtHi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setByteExtHi(int newByteExtHi)
  {
    int oldByteExtHi = byteExtHi;
    byteExtHi = newByteExtHi;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AfpTextPackage.OBJECT_BYTE_EXTENT__BYTE_EXT_HI, oldByteExtHi, byteExtHi));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AfpTextPackage.OBJECT_BYTE_EXTENT__BYTE_EXT:
        return getByteExt();
      case AfpTextPackage.OBJECT_BYTE_EXTENT__BYTE_EXT_HI:
        return getByteExtHi();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AfpTextPackage.OBJECT_BYTE_EXTENT__BYTE_EXT:
        setByteExt((Integer)newValue);
        return;
      case AfpTextPackage.OBJECT_BYTE_EXTENT__BYTE_EXT_HI:
        setByteExtHi((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AfpTextPackage.OBJECT_BYTE_EXTENT__BYTE_EXT:
        setByteExt(BYTE_EXT_EDEFAULT);
        return;
      case AfpTextPackage.OBJECT_BYTE_EXTENT__BYTE_EXT_HI:
        setByteExtHi(BYTE_EXT_HI_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AfpTextPackage.OBJECT_BYTE_EXTENT__BYTE_EXT:
        return byteExt != BYTE_EXT_EDEFAULT;
      case AfpTextPackage.OBJECT_BYTE_EXTENT__BYTE_EXT_HI:
        return byteExtHi != BYTE_EXT_HI_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ByteExt: ");
    result.append(byteExt);
    result.append(", ByteExtHi: ");
    result.append(byteExtHi);
    result.append(')');
    return result.toString();
  }

} //ObjectByteExtentImpl
