/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText.impl;

import org.afplib.afpText.AfpTextPackage;
import org.afplib.afpText.ObjectAreaSize;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Object Area Size</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.afplib.afpText.impl.ObjectAreaSizeImpl#getSizeType <em>Size Type</em>}</li>
 *   <li>{@link org.afplib.afpText.impl.ObjectAreaSizeImpl#getXoaSize <em>Xoa Size</em>}</li>
 *   <li>{@link org.afplib.afpText.impl.ObjectAreaSizeImpl#getYoaSize <em>Yoa Size</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ObjectAreaSizeImpl extends tripletImpl implements ObjectAreaSize
{
  /**
   * The default value of the '{@link #getSizeType() <em>Size Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSizeType()
   * @generated
   * @ordered
   */
  protected static final int SIZE_TYPE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSizeType() <em>Size Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSizeType()
   * @generated
   * @ordered
   */
  protected int sizeType = SIZE_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getXoaSize() <em>Xoa Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getXoaSize()
   * @generated
   * @ordered
   */
  protected static final int XOA_SIZE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getXoaSize() <em>Xoa Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getXoaSize()
   * @generated
   * @ordered
   */
  protected int xoaSize = XOA_SIZE_EDEFAULT;

  /**
   * The default value of the '{@link #getYoaSize() <em>Yoa Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getYoaSize()
   * @generated
   * @ordered
   */
  protected static final int YOA_SIZE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getYoaSize() <em>Yoa Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getYoaSize()
   * @generated
   * @ordered
   */
  protected int yoaSize = YOA_SIZE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ObjectAreaSizeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AfpTextPackage.eINSTANCE.getObjectAreaSize();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getSizeType()
  {
    return sizeType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSizeType(int newSizeType)
  {
    int oldSizeType = sizeType;
    sizeType = newSizeType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AfpTextPackage.OBJECT_AREA_SIZE__SIZE_TYPE, oldSizeType, sizeType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getXoaSize()
  {
    return xoaSize;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setXoaSize(int newXoaSize)
  {
    int oldXoaSize = xoaSize;
    xoaSize = newXoaSize;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AfpTextPackage.OBJECT_AREA_SIZE__XOA_SIZE, oldXoaSize, xoaSize));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getYoaSize()
  {
    return yoaSize;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setYoaSize(int newYoaSize)
  {
    int oldYoaSize = yoaSize;
    yoaSize = newYoaSize;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AfpTextPackage.OBJECT_AREA_SIZE__YOA_SIZE, oldYoaSize, yoaSize));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AfpTextPackage.OBJECT_AREA_SIZE__SIZE_TYPE:
        return getSizeType();
      case AfpTextPackage.OBJECT_AREA_SIZE__XOA_SIZE:
        return getXoaSize();
      case AfpTextPackage.OBJECT_AREA_SIZE__YOA_SIZE:
        return getYoaSize();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AfpTextPackage.OBJECT_AREA_SIZE__SIZE_TYPE:
        setSizeType((Integer)newValue);
        return;
      case AfpTextPackage.OBJECT_AREA_SIZE__XOA_SIZE:
        setXoaSize((Integer)newValue);
        return;
      case AfpTextPackage.OBJECT_AREA_SIZE__YOA_SIZE:
        setYoaSize((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AfpTextPackage.OBJECT_AREA_SIZE__SIZE_TYPE:
        setSizeType(SIZE_TYPE_EDEFAULT);
        return;
      case AfpTextPackage.OBJECT_AREA_SIZE__XOA_SIZE:
        setXoaSize(XOA_SIZE_EDEFAULT);
        return;
      case AfpTextPackage.OBJECT_AREA_SIZE__YOA_SIZE:
        setYoaSize(YOA_SIZE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AfpTextPackage.OBJECT_AREA_SIZE__SIZE_TYPE:
        return sizeType != SIZE_TYPE_EDEFAULT;
      case AfpTextPackage.OBJECT_AREA_SIZE__XOA_SIZE:
        return xoaSize != XOA_SIZE_EDEFAULT;
      case AfpTextPackage.OBJECT_AREA_SIZE__YOA_SIZE:
        return yoaSize != YOA_SIZE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (SizeType: ");
    result.append(sizeType);
    result.append(", XoaSize: ");
    result.append(xoaSize);
    result.append(", YoaSize: ");
    result.append(yoaSize);
    result.append(')');
    return result.toString();
  }

} //ObjectAreaSizeImpl
