/**
 * generated by Xtext 2.18.0.M3
 */
package org.afplib.afpText.impl;

import org.afplib.afpText.AfpTextPackage;
import org.afplib.afpText.PresentationSpaceMixingRules;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Presentation Space Mixing Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PresentationSpaceMixingRulesImpl extends tripletImpl implements PresentationSpaceMixingRules
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PresentationSpaceMixingRulesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AfpTextPackage.eINSTANCE.getPresentationSpaceMixingRules();
  }

} //PresentationSpaceMixingRulesImpl
